{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "service" "billing" "global" .) | fromYaml }}
{{- if ($service.enabled | default false) }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- $webSvc:= include "common.service" (dict "service" "web" "global" .) | fromYaml }}
  {{- $webName := include "common.names.custom" (list . $webSvc.name) }}
  {{- $webPort := dig "service" "port" 8000 $webSvc }}
  config.sh: |
    #!/bin/sh
    mkdir -p /app/config
    cat <<EOF > /app/config/config.yaml
    nats: $NATS_URL
    pub:
      addr: :8080
      key: ''
    sub:
      streams:
        - name: accountingNotifyStream
          consumers:
            - durable_name: starship-billing-durable-consumer
      webhook:
        url: http://{{ $webName }}:{{ $webPort }}/api/v1/platforms/billing-events/
        key: 'key'
    EOF
{{- end }}