{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "ctx" . "service" "loki") | fromYaml }}
{{- if $service.gatewayAuth.htpasswd }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $defaultHtpasswd := $service.gatewayAuth.htpasswd }}
  .htpasswd: {{ $defaultHtpasswd | required "loki.gatewayAuth.htpasswd is required" | b64enc | quote }}
{{- end }}
