{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "accounting") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "accounting") | nindent 4 }}
spec:
  type: {{ .Values.csghub.accounting.service.type }}
  ports:
    - port: {{ .Values.csghub.accounting.service.port }}
      targetPort: 8086
      protocol: TCP
      name: accounting
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "accounting") | nindent 4 }}