{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $objectStoreConfig := include "chart.objectStoreConfig" (dict "service" .Values.server "global" .) | fromYaml }}
{{- $redisConfig := include "csghub.redis.config" (dict "service" .Values.server "global" .) | fromYaml }}
{{- $pgConfig := include "csghub.postgresql.config" (dict "service" .Values.server "global" .) | fromYaml }}
{{- $gitConfig := include "csghub.gitaly.config" (dict "service" .Values.server "global" .) | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" (list . "server") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "server") | nindent 4 }}
data:
  GIN_MODE: release
  {{- if eq .Values.global.edition "saas" }}
  STARHUB_SERVER_SAAS: "true"
  {{- else }}
  STARHUB_SERVER_SAAS: "false"
  {{- end }}
  STARHUB_SERVER_MIRRORSERVER_ENABLE: "false"
  STARHUB_SERVER_MIRRORSERVER_HOST: ""
  {{- $token := include "server.hub.api.token" . }}
  {{- $tokenConfigMap := include "common.names.custom" (list . "server") -}}
  {{- $tokenConfigMapData := (lookup "v1" "ConfigMap" .Release.Namespace $tokenConfigMap).data }}
  {{- if $tokenConfigMapData }}
  {{- $tokenFromConfigMap := index $tokenConfigMapData "STARHUB_SERVER_API_TOKEN" }}
  {{- if eq (len $tokenFromConfigMap) 128 }}
  {{- $token = $tokenFromConfigMap }}
  {{- end }}
  {{- end }}
  STARHUB_SERVER_API_TOKEN: {{ $token | quote }}
  STARHUB_SERVER_MIRROR_REMOTE: "false"
  STARHUB_SERVER_MODEL_DOWNLOAD_ENDPOINT: {{ include "csghub.external.endpoint" . | quote }}
  STARHUB_JWT_SIGNING_KEY: "e2kk6awudc3620ed9a"

  # Multiple-Sync Enabled/Disabled
  STARHUB_SERVER_MULTI_SYNC_ENABLED: {{ .Values.server.multiSync.enabled | quote }}
  # Multiple-Sync fetch timeout
  STARHUB_SERVER_GIT_OPERATION_TIMEOUT: "120"

  # Redis Connection Info
  STARHUB_SERVER_REDIS_ENDPOINT: {{ printf "%s:%v" $redisConfig.host $redisConfig.port | quote }}
  {{- if not .Values.global.redis.enabled }}
  STARHUB_SERVER_REDIS_PASSWORD: {{ $redisConfig.password | quote }}
  {{- end }}

  # PostgreSQL Connection Info
  STARHUB_DATABASE_HOST: {{ $pgConfig.host | quote }}
  STARHUB_DATABASE_PORT: {{ $pgConfig.port | quote }}
  STARHUB_DATABASE_USERNAME: {{ $pgConfig.user | quote }}
  STARHUB_DATABASE_PASSWORD: {{ $pgConfig.password | quote }}
  STARHUB_DATABASE_NAME: {{ $pgConfig.database | quote }}
  STARHUB_DATABASE_TIMEZONE: {{ $pgConfig.timezone | quote }}
  STARHUB_DATABASE_DSN: {{ include "csghub.postgresql.url" (dict "service" .Values.server "global" .) | quote }}

  # Object Storage Connection Info
  STARHUB_SERVER_S3_ENDPOINT: {{ $objectStoreConfig.externalEndpoint | trimPrefix "http://" | trimPrefix "https://" | quote }}
  {{- if not .Values.global.objectStore.enabled }}
  STARHUB_SERVER_S3_ACCESS_KEY_ID: {{ $objectStoreConfig.accessKey | quote }}
  STARHUB_SERVER_S3_ACCESS_KEY_SECRET: {{ $objectStoreConfig.secretKey | quote }}
  {{- end }}
  STARHUB_SERVER_S3_BUCKET: {{ $objectStoreConfig.bucket | quote }}
  STARHUB_SERVER_S3_REGION: {{ $objectStoreConfig.region | quote }}
  STARHUB_SERVER_S3_ENABLE_SSL: {{ $objectStoreConfig.secure | quote }}
  {{- if $objectStoreConfig.pathStyle }}
  STARHUB_SERVER_S3_BUCKET_LOOKUP: "path"
  {{- else }}
  STARHUB_SERVER_S3_BUCKET_LOOKUP: "auto"
  {{- end }}
  STARHUB_SERVER_SKIP_LFS_FILE_VALIDATION: {{ .Values.server.objectStore.directUpload | default false | quote }}

  # Gitaly Connection Info
  STARHUB_SERVER_GITSERVER_TYPE: "gitaly"
  STARHUB_SERVER_GITALY_SERVER_SOCKET: {{ include "csghub.gitaly.grpcEndpoint" (dict "service" .Values.server "global" .) | quote }}
  STARHUB_SERVER_GITALY_TOKEN: {{ $gitConfig.token | quote }}
  STARHUB_SERVER_GITALY_STORAGE: {{ $gitConfig.storage | quote }}
  STARHUB_SERVER_CHECK_FILE_SIZE_ENABLED: {{ not $gitConfig.isCluster | quote }}
  {{- if eq (include "gitlab-shell.external.port" .) "22" }}
  STARHUB_SERVER_SSH_DOMAIN: {{ printf "ssh://git@%s" (include "csghub.external.domain" .) | quote }}
  {{- else }}
  STARHUB_SERVER_SSH_DOMAIN: {{ printf "ssh://git@%s:%s" (include "csghub.external.domain" .) (include "gitlab-shell.external.port" .) | quote }}
  {{- end }}

  # Accounting
  OPENCSG_ACCOUNTING_SERVER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "accounting")) | quote }}
  OPENCSG_ACCOUNTING_SERVER_PORT: {{ include "csghub.svc.port" "accounting" | quote }}

  # User
  OPENCSG_USER_SERVER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "user")) | quote }}
  OPENCSG_USER_SERVER_PORT: {{ include "csghub.svc.port" "user" | quote }}

  # Space Application
  STARHUB_SERVER_PUBLIC_DOMAIN: {{ include "csghub.external.endpoint" . | quote }}
  STARHUB_SERVER_MODEL_DOCKER_REG_BASE: {{ .Values.server.model.registry | default (or .Values.global.image.registry "docker.io") | quote }}

  # Deprecated ==> re-enabled
  {{- if .Values.global.usePublicDomain }}
  STARHUB_SERVER_PUBLIC_ROOT_DOMAIN: {{ include "csghub.external.public.endpoint" . | trimPrefix "http://" | trimPrefix "https://" | quote }}
  {{- else }}
  STARHUB_SERVER_PUBLIC_ROOT_DOMAIN: ""
  {{- end }}

  # Deprecated
  STARHUB_SERVER_INTERNAL_ROOT_DOMAIN: {{ printf "%s.app.internal:%s" (include "namespace.spaces" .) (include "csghub.svc.port" "rproxy") | quote }}

  # Casdoor
  STARHUB_SERVER_CASDOOR_CERTIFICATE: "/starhub-bin/casdoor/tls.crt"

  # Workflow
  OPENCSG_WORKFLOW_SERVER_ENDPOINT: {{ include "temporal.internal.endpoint" . | quote }}

  # Dataflow
  OPENCSG_DATAFLOW_SERVER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "dataflow")) | quote }}
  OPENCSG_DATAFLOW_SERVER_PORT: {{ include "csghub.svc.port" "dataflow" | quote }}

  # Dataviewer
  OPENCSG_DATAVIEWER_SERVER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "dataviewer")) | quote }}
  OPENCSG_DATAVIEWER_SERVER_PORT: {{ include "csghub.svc.port" "dataviewer" | quote }}

  # Moderation
  {{- if .Values.global.moderation.enabled }}
  STARHUB_SERVER_SENSITIVE_CHECK_ENABLE: "true"
  OPENCSG_MODERATION_SERVER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "gateway")) | quote }}
  OPENCSG_MODERATION_SERVER_PORT: {{ include "csghub.svc.port" "moderation" | quote }}
  {{- else }}
  STARHUB_SERVER_SENSITIVE_CHECK_ENABLE: "false"
  {{- end }}

  STARHUB_SERVER_CRON_JOB_SYNC_AS_CLIENT_CRON_EXPRESSION: '*/5 * * * *'

  # Tracing logging
  {{- if .Values.tempo.enabled }}
  OPENCSG_TRACING_OTLP_ENDPOINT: {{ printf "http://%s:4317" (include "common.names.custom" (list . "tempo")) }}
  {{- end }}
  OPENCSG_TRACING_OTLP_LOGGING: "false"

  STARHUB_SERVER_SPACE_PYPI_INDEX_URL: {{ .Values.global.pipIndexUrl | quote }}

  # Notification
  STARHUB_SERVER_NOTIFIER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "notification")) | quote }}
  STARHUB_SERVER_NOTIFIER_PORT: {{ include "csghub.svc.port" "notification" | quote }}
  {{- with .Values.notification.smtp }}
  STARHUB_SERVER_MAILER_HOST: {{ .host | quote }}
  STARHUB_SERVER_MAILER_PORT: {{ .port | quote }}
  STARHUB_SERVER_MAILER_USERNAME: {{ .username | quote }}
  STARHUB_SERVER_MAILER_PASSWORD: {{ .password | quote }}
  {{- end }}
  STARHUB_SERVER_REPO_SYNC_TIMEZONE: {{ .Values.notification.repoSyncTime | default "Asia/Shanghai" | quote }}
  STARHUB_SERVER_NOTIFIER_BROADCAST_USER_PAGE_SIZE: {{ .Values.notification.broadcastUserPageSize | default 100 | quote }}
  STARHUB_SERVER_NOTIFIER_BROADCAST_EMAIL_PAGE_SIZE: {{ .Values.notification.broadcastEmailPageSize | default 100 | quote }}

  # FeiShu Integration
  {{- if eq (include "csghub.edition.suffix" .) "ee" }}
  {{- with .Values.notification.feiShu }}
  STARHUB_SERVER_FEISHU_APP_ID: {{ .appId | quote }}
  STARHUB_SERVER_FEISHU_APP_SECRET: {{ .appSecret | quote }}
  STARHUB_SERVER_FEISHU_BATCH_SEND_MESSAGE_CRON_EXPRESSION: {{ .batchSendMessageCronExpression | default "*/10 * * * *" | quote }}
  STARHUB_SERVER_FEISHU_MAX_REQUEST_CONTENT_SIZE: {{ .maxRequestContentSize | default 20480 | quote }}
  STARHUB_SERVER_FEISHU_MAX_DELAY_DURATION: {{ .maxDelayDuration | default 3600 | quote }}
  STARHUB_SERVER_FEISHU_CHAT_IDS_CACHE_TTL: {{ .chatIdsCacheTTL | default 21600 | quote }}
  {{- end }}
  {{- end }}

  {{- if not (regexMatch "^ee$|^ce$" (.Values.global.edition | toString)) }}
  OPENCSG_PAYMENT_SERVER_IS_PROD: "true"
  OPENCSG_PAYMENT_BILL_BUCKET: "csghub-billing"
  OPENCSG_PAYMENT_SERVER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "payment")) | quote }}
  OPENCSG_PAYMENT_SERVER_PORT: {{ include "csghub.svc.port" "payment" | quote }}
  {{- end }}

  {{- if .Values.server.swagger.enabled }}
  STARHUB_SERVER_ENABLE_SWAGGER: "true"
  {{- end }}

  {{- if .Values.server.multiSync.proxy.enabled }}
  {{- with .Values.server.multiSync.proxy }}
  STARHUB_SERVER_PROXY_ENABLE: "true"
  STARHUB_SERVER_PROXY_URL: {{ .address | quote }}
  STARHUB_SERVER_PROXY_HOSTS: {{ .hosts | quote }}
  {{- end }}
  {{- end }}

  # Prometheus
  {{- if .Values.prometheus.enabled }}
  STARHUB_SERVER_PROMETHEUS_API_ADDRESS: {{ printf "http://%s:80/api/v1/query" (include "common.names.custom" (list . "prometheus-server")) }}
  {{- with .Values.prometheus.ingress.basicAuth }}
  STARHUB_SERVER_PROMETHEUS_BASIC_AUTH: {{ printf "%s:%s" .username .password | b64enc | quote }}
  {{- end }}
  {{- end }}

  STARHUB_SERVER_LFS_SYNC_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "mirror-lfs")) }}
