{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" (list . "server-init") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "server-init") | nindent 4 }}
data:
  {{- $currentScope := . }}
  {{- range $path, $_ := .Files.Glob "scripts/*.sql" }}
    {{- with $currentScope }}
    {{- base $path | nindent 2 }}: |
      {{- .Files.Get $path | nindent 4 }}
    {{- end }}
  {{- end }}
