{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $objectStoreConfig := include "chart.objectStoreConfig" (dict "service" .Values.portal "global" .) | fromYaml }}
{{- $pgConfig := include "csghub.postgresql.config" (dict "service" .Values.portal "global" .) | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" (list . "portal") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "portal") | nindent 4 }}
data:
  CSGHUB_PORTAL_APP_ENV: "production"
  {{- if eq (include "global.ingress.tls.enabled" .) "true" }}
  CSGHUB_PORTAL_ENABLE_HTTPS: "true"
  {{- else }}
  CSGHUB_PORTAL_ENABLE_HTTPS: "false"
  {{- end }}
  CSGHUB_PORTAL_ON_PREMISE: "true"
  {{- if .Values.global.moderation.enabled }}
  CSGHUB_PORTAL_SENSITIVE_CHECK: "true"
  {{- else }}
  CSGHUB_PORTAL_SENSITIVE_CHECK: "false"
  {{- end }}
  CSGHUB_PORTAL_STARHUB_BASE_URL: {{ include "csghub.external.endpoint" . | quote }}
  CSGHUB_PORTAL_STARHUB_API_KEY: {{ include "server.hub.api.token" . | quote }}
  # PostgreSQL
  CSGHUB_PORTAL_DATABASE_HOST: {{ $pgConfig.host | quote }}
  CSGHUB_PORTAL_DATABASE_PORT: {{ $pgConfig.port | quote }}
  CSGHUB_PORTAL_DATABASE_NAME: {{ $pgConfig.database | quote }}
  CSGHUB_PORTAL_DATABASE_USERNAME: {{ $pgConfig.user | quote }}
  CSGHUB_PORTAL_DATABASE_PASSWORD: {{ $pgConfig.password | quote }}
  CSGHUB_PORTAL_DATABASE_DSN: {{ include "csghub.postgresql.url" (dict "service" .Values.portal "global" .) | quote }}
  # ObjectStorage
  CSGHUB_PORTAL_S3_ENDPOINT: {{ $objectStoreConfig.externalEndpoint | trimPrefix "http://" | trimPrefix  "https://" | quote }}
  {{- $s3DefaultEndpoint := $objectStoreConfig.externalEndpoint | trimPrefix "http://" | trimPrefix  "https://" }}
  CSGHUB_PORTAL_PRIVATE_S3_ENDPOINT: {{ .Values.portal.additionalObjectStore.endpoint | default $s3DefaultEndpoint | quote }}
  {{- if not .Values.global.objectStore.enabled }}
  CSGHUB_PORTAL_S3_ACCESS_KEY_ID: {{ $objectStoreConfig.accessKey | quote }}
  CSGHUB_PORTAL_S3_ACCESS_KEY_SECRET: {{ $objectStoreConfig.secretKey | quote }}
  CSGHUB_PORTAL_PRIVATE_S3_ACCESS_KEY_ID: {{ .Values.portal.additionalObjectStore.accessKey | default $objectStoreConfig.accessKey | quote }}
  CSGHUB_PORTAL_PRIVATE_S3_ACCESS_KEY_SECRET: {{ .Values.portal.additionalObjectStore.secretKey | default $objectStoreConfig.secretKey | quote }}
  {{- end }}
  CSGHUB_PORTAL_S3_BUCKET: {{ $objectStoreConfig.bucket | quote }}
  CSGHUB_PORTAL_S3_REGION: {{ $objectStoreConfig.region | quote }}
  CSGHUB_PORTAL_S3_ENABLE_SSL: {{ $objectStoreConfig.secure | quote }}
  CSGHUB_PORTAL_PRIVATE_S3_BUCKET: {{ .Values.portal.additionalObjectStore.bucket | default $objectStoreConfig.bucket | quote }}
  CSGHUB_PORTAL_PRIVATE_S3_REGION: {{ .Values.portal.additionalObjectStore.region | default $objectStoreConfig.region | quote }}
  CSGHUB_PORTAL_PRIVATE_S3_ENABLE_SSL: {{ .Values.portal.additionalObjectStore.secure | default $objectStoreConfig.secure | quote }}
  # SMTP
  {{- with .Values.portal.smtp }}
  CSGHUB_PORTAL_MAILER_HOST: {{ .host | quote }}
  CSGHUB_PORTAL_MAILER_PORT: {{ .port | quote }}
  CSGHUB_PORTAL_MAILER_USERNAME: {{ .username | quote }}
  CSGHUB_PORTAL_MAILER_PASSWORD: {{ .password | quote }}
  {{- end }}
