{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.global.deploy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" (list . "runner") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "runner") | nindent 4 }}
data:
  # Specify the namespace to use and select it based on the environment
  {{- $imageBuilderNamespace := .Values.global.deploy.imageBuilder.namespace }}
  {{- if eq .Values.global.deploy.mergingNamespace "Multi" }}
    {{- $imageBuilderNamespace = .Values.global.deploy.namespace }}
  {{- else if eq .Values.global.deploy.mergingNamespace "Single" }}
    {{- $imageBuilderNamespace = .Release.Namespace }}
  {{- end }}
  STARHUB_SERVER_RUNNER_IMAGE_BUILDER_NAMESPACE: {{ $imageBuilderNamespace }}
  # The image used by the pod needs to be accessible in the pod
  STARHUB_SERVER_RUNNER_IMAGE_BUILDER_GIT_IMAGE: {{ include "image.fixed.prefix" (list . "alpine/git:2.36.2") }}
  STARHUB_SERVER_RUNNER_IMAGE_BUILDER_KANIKO_IMAGE: {{ include "image.fixed.prefix" (list . "bitnami/kaniko:1.23.2") }}
  # The cleanup time after the image builder task is completed, the default is 2 minutes
  STARHUB_SERVER_RUNNER_IMAGE_BUILDER_JOB_TTL: "300"
  # Task status correction time, default is 5 minutes
  STARHUB_SERVER_RUNNER_IMAGE_BUILDER_STATUS_TTL: "300"
  {{- if or .Values.global.registry.enabled .Values.global.registry.insecure }}
  STARHUB_SERVER_RUNNER_IMAGE_BUILDER_KANIKO_ARGS: "--skip-tls-verify,--insecure,--compressed-caching=false,--single-snapshot,--build-arg=PyPI={{ .Values.global.deploy.pipIndexUrl }},--build-arg=HF_ENDPOINT={{ printf "%s/hf" (include "csghub.external.endpoint" .) }}"
  {{- else }}
  STARHUB_SERVER_RUNNER_IMAGE_BUILDER_KANIKO_ARGS: "--compressed-caching=false,--single-snapshot,--build-arg=PyPI={{ .Values.global.deploy.pipIndexUrl }},--build-arg=HF_ENDPOINT={{ printf "%s/hf" (include "csghub.external.endpoint" .) }}"
  {{- end }}
  {{- $argoWorkflowNamespace := "workflows" }}
  {{- $argoWorkflowQuotaNamespace := "workflows-quota" }}
  {{- if eq .Values.global.deploy.mergingNamespace "Multi" }}
  {{- $argoWorkflowNamespace = .Values.global.deploy.namespace }}
  {{- $argoWorkflowQuotaNamespace = .Values.global.deploy.namespace }}
  {{- else if eq .Values.global.deploy.mergingNamespace "Single" }}
  {{- $argoWorkflowNamespace = .Release.Namespace }}
  {{- $argoWorkflowQuotaNamespace = .Release.Namespace }}
  {{- end }}
  STARHUB_SERVER_ARGO_NAMESPACE: {{ $argoWorkflowNamespace }}
  STARHUB_SERVER_ARGO_QUOTA_NAMESPACE: {{ $argoWorkflowQuotaNamespace }}
---
{{- end }}
