{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.custom" (list . "portal") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "portal") | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
    {{- with .Values.csghub.portal.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "portal") | nindent 6 }}
  replicas: {{ .Values.csghub.portal.replicas }}
  revisionHistoryLimit: 1
  minReadySeconds: 60
  template:
    metadata:
      annotations:
        {{- with .Values.csghub.portal.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels" (dict "context" . "service" "portal") | nindent 8 }}
    spec:
      {{- with (or .Values.csghub.portal.image.pullSecrets .Values.global.image.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.csghub.portal.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.csghub.portal.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.custom" (list . "portal") }}
      automountServiceAccountToken: {{ .Values.csghub.portal.serviceAccount.automount }}
      {{- end }}
      initContainers:
        - name: wait-for-server
          image: {{ include "image.fixed.prefix" (list . "busybox:latest") }}
          imagePullPolicy: {{ or .Values.csghub.server.image.pullPolicy .Values.global.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until nc -z {{ include "common.names.custom" (list . "server") }} {{ include "csghub.svc.port" "server" }}; do echo 'Wait for csghub-server to be ready'; sleep 2; done" ]
      containers:
        - name: portal
          {{- $tag := include "csghub.image.tag" (dict "tag" (or .Values.csghub.portal.image.tag .Values.global.image.tag) "context" .) }}
          {{- $_ := set .Values.csghub.portal.image "tag" $tag }}
          image: {{ include "image.generic.prefix" (list . .Values.csghub.portal.image) }}
          imagePullPolicy: {{ or .Values.csghub.server.image.pullPolicy .Values.global.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "./csghub-portal migration init && ./csghub-portal migration migrate && ./csghub-portal db seed && ./csghub-portal start server" ]
          ports:
            - containerPort: 8090
              name: portal
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" (list . "portal") }}
            - configMapRef:
                name: {{ include "common.names.custom" (list . "server") }}
            - configMapRef:
                name: {{ include "common.names.custom" (list . "casdoor") }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "nats") }}
            {{- if .Values.global.objectStore.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "minio") }}
            {{- end }}
          env:
            - name: CSGHUB_PORTAL_LOGIN_URL
              value: "{{ include "casdoor.external.endpoint" . }}/login/oauth/authorize?client_id=$(STARHUB_SERVER_CASDOOR_CLIENT_ID)&response_type=code&redirect_uri=$(CSGHUB_PORTAL_STARHUB_BASE_URL)/api/v1/callback/casdoor&scope=read&state=casdoor"
            {{- if .Values.global.objectStore.enabled }}
            - name: CSGHUB_PORTAL_S3_ACCESS_KEY_ID
              value: "$(MINIO_ROOT_USER)"
            - name: CSGHUB_PORTAL_S3_ACCESS_KEY_SECRET
              value: "$(MINIO_ROOT_PASSWORD)"
            - name: CSGHUB_PORTAL_PRIVATE_S3_ACCESS_KEY_ID
              value: {{ .Values.csghub.portal.additionalObjectStore.accessKey | default "$(MINIO_ROOT_USER)" | quote }}
            - name: CSGHUB_PORTAL_PRIVATE_S3_ACCESS_KEY_SECRET
              value: {{ .Values.csghub.portal.additionalObjectStore.secretKey | default "$(MINIO_ROOT_PASSWORD)" | quote }}
            {{- end }}
            {{- with .Values.csghub.portal.environments }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- if .Values.csghub.autoscaling.enabled }}
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 10
          securityContext:
            {{- .Values.csghub.portal.podSecurityContext | toYaml | nindent 12 }}
      {{- with .Values.csghub.portal.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.csghub.portal.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.csghub.portal.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}