{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
{{- $gitConfig := include "csghub.gitaly.config" (dict "service" .Values.server "global" .) | fromYaml }}
{{- $redisConfig := include "csghub.redis.config" (dict "service" .Values.server "global" .) | fromYaml }}
kind: Deployment
metadata:
  name: {{ include "common.names.custom" (list . "server") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "server") | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
    {{- with .Values.server.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "server") | nindent 6 }}
  replicas: {{ .Values.server.replicas }}
  revisionHistoryLimit: 1
  minReadySeconds: 30
  template:
    metadata:
      annotations:
        {{- with .Values.server.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels" (dict "context" . "service" "server") | nindent 8 }}
    spec:
      {{- with (or .Values.server.image.pullSecrets .Values.global.image.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.server.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.server.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.custom" (list . "server") }}
      automountServiceAccountToken: {{ .Values.server.serviceAccount.automount }}
      {{- end }}
      initContainers:
        - name: wait-for-redis
          image: {{ include "image.fixed.prefix" (list . "redis:7.2.5") }}
          imagePullPolicy: {{ or .Values.server.image.pullPolicy .Values.global.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              until redis-cli -h {{ $redisConfig.host }} -p {{ $redisConfig.port }} -a {{ $redisConfig.password }} ping;
              do
                echo 'Wait for Redis to be ready';
                sleep 2;
              done
        - name: wait-for-postgresql
          image: {{ include "image.fixed.prefix" (list . "opencsghq/psql:latest") }}
          imagePullPolicy: {{ or .Values.server.image.pullPolicy .Values.global.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              until psql {{ include "csghub.postgresql.dsn" (dict "service" .Values.server "global" .) | quote }} -c 'SELECT 1';
              do
                echo 'Wait for PostgreSQL to be ready';
                sleep 2;
              done
        - name: wait-for-gitaly
          image: {{ include "image.fixed.prefix" (list . "busybox:latest") }}
          imagePullPolicy: {{ or .Values.server.image.pullPolicy .Values.global.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              until nc -z {{ $gitConfig.host }} {{ $gitConfig.port }};
              do
                echo 'Wait for gitaly to be ready';
                sleep 2;
              done
        - name: wait-for-nats
          image: {{ include "image.fixed.prefix" (list . "busybox:latest") }}
          imagePullPolicy: {{ or .Values.server.image.pullPolicy .Values.global.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              until nc -z {{ include "nats.internal.domain" . }} {{ include "nats.internal.ports.api" . }};
              do
                cho 'Wait for nats to be ready';
                sleep 2;
              done
        - name: wait-for-temporal
          image: {{ include "image.fixed.prefix" (list . "busybox:latest") }}
          imagePullPolicy: {{ or .Values.server.image.pullPolicy .Values.global.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              until nc -z {{ include "temporal.internal.domain" . }} {{ include "temporal.internal.port" . }};
              do
                cho 'Wait for temporal to be ready';
                sleep 2;
              done
      containers:
        - name: server
          {{- $tag := include "csghub.image.tag" (dict "tag" (or .Values.server.image.tag .Values.global.image.tag) "context" .) }}
          {{- $_ := set .Values.server.image "tag" $tag }}
          image: {{ include "image.generic.prefix" (list . .Values.server.image) }}
          imagePullPolicy: {{ or .Values.server.image.pullPolicy .Values.global.image.pullPolicy }}
          command: [ "/starhub-bin/starhub", "start", "server", "-l", {{ .Values.server.logging.level | default "info" | quote }} ]
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" (list . "core") }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "nats") }}
          {{- with .Values.server.environments }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- if .Values.autoscaling.enabled }}
            requests:
              cpu: {{ .Values.server.resources.requests.cpu | default "100m" }}
              memory: {{ .Values.server.resources.requests.memory | default "256Mi" }}
            limits:
              cpu: {{ .Values.server.resources.limits.cpu | default "300m" }}
              memory: {{ .Values.server.resources.limits.memory | default "512Mi" }}
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          securityContext:
            {{- .Values.server.podSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: jwt-token-crt
              mountPath: /starhub-bin/casdoor
      volumes:
        - name: jwt-token-crt
          secret:
            secretName: {{ include "common.names.custom" (list . "casdoor") }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
