{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy-metrics
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: listeners
    gateway.envoyproxy.io/owning-gateway-namespace: csghub
  ports:
    - name: metrics
      protocol: TCP
      port: 19001
      targetPort: 19001
