{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $secretName := include "common.names.custom" (list . "secrets") }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $existingData := ($existingSecret.data) | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  master-key: {{ include "common.secret.masterKey" . | b64enc | quote }}
  csghub-token: {{ include "csghub.api.token" . | b64enc | quote }}
  agenticflow-token: {{ include "agenticflow.api.token" . | b64enc | quote }}
  jwt-signing-key: {{ include "common.secret.value" (list . "jwt-signing-key" 40) | b64enc | quote }}
  space-session-secret-key: {{ include "common.secret.value" (list . "space-session-secret-key" 40) | b64enc | quote }}
  superset-secret-key: {{ include "common.secret.value" (list . "superset-secret-key" 56) | b64enc | quote }}
