{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $namespace := .Values.global.deploy.namespace }}
{{- if eq .Values.global.deploy.mergingNamespace "Single" }}
  {{- $namespace = .Release.Namespace }}
{{- end }}
{{- $registryConfig := include "chart.registryConfig" (dict "service" .Values.csghub.runner "global" .) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" (list . "docker-credential") }}
  namespace: {{ $namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $registryConfig.registry $registryConfig.username $registryConfig.password (printf "%s:%s" $registryConfig.username $registryConfig.password | b64enc) | b64enc }}
