{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.prometheus.ingress.enabled }}
{{- $secretPrometheus := include "common.names.custom" (list . "prome-basic-auth") }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace $secretPrometheus).data -}}
{{- $username := .Values.prometheus.ingress.basicAuth.username -}}
{{- $password := or .Values.prometheus.ingress.basicAuth.password (randAlpha 15) -}}
{{- $htpasswd := htpasswd $username $password }}
{{- if $secretData }}
{{- $secretAuth := index $secretData "auth" }}
{{- if $secretAuth }}
{{- $htpasswd = $secretAuth | b64dec }}
{{- end }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretPrometheus }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  auth: {{ $htpasswd | b64enc }}
{{- end }}
---
{{- if .Values.loki.ingress.enabled }}
{{- $secretLoki := include "common.names.custom" (list . "loki-basic-auth") }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace $secretLoki).data -}}
{{- $username := .Values.loki.ingress.basicAuth.username -}}
{{- $password := or .Values.loki.ingress.basicAuth.password (randAlpha 15) -}}
{{- $htpasswd := htpasswd $username $password }}
{{- if $secretData }}
{{- $secretAuth := index $secretData "auth" }}
{{- if $secretAuth }}
{{- $htpasswd = $secretAuth | b64dec }}
{{- end }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretLoki }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  auth: {{ $htpasswd | b64enc }}
{{- end }}