{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" . | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- if $service.rbac.create }}
{{- $runnerArgoRole := printf "%s-argo-workflow-executor" $serviceName }}
{{- $argoWorkflowRole := printf "%s-argo-workflow-executor" .Release.Name }}
{{- $spaceNamespace := include "namespace.spaces" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
---
## --- Resourcequota and namespace management permissions for spaces namespace ---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $serviceName }}
  namespace: {{ $spaceNamespace }}
rules:
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames: [{{ $spaceNamespace | quote }}]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["", "apps", "serving.knative.dev", "argoproj.io"]
    resources: ["pods", "pods/log", "services", "deployments", "configmaps", "workflows", "workflowtemplates"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceName }}
  namespace: {{ $spaceNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $serviceName }}
  apiGroup: rbac.authorization.k8s.io
---
## --- Executor role permissions in image-factory namespace ---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $runnerArgoRole }}
  namespace: {{ $spaceNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $argoWorkflowRole }}
  apiGroup: rbac.authorization.k8s.io
{{- if ne (include "namespace.spaces" .) .Release.Namespace }}
---
## --- Cluster-wide nodes and pods viewing permissions ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $serviceName }}
rules:
  - apiGroups: ["", "metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $serviceName }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $serviceName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
