{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" . | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- $secretName := include "common.names.custom" (list . "docker-credential") }}
{{- $spaceName := include "namespace.spaces" . }}
{{- $secretExists := lookup "v1" "Secret" $spaceName $secretName }}
{{- if not $secretExists }}
{{- $registryConfig := include "common.registry.config" (dict "ctx" . "service" $service) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $spaceName }}
  labels:
    app.kubernetes.io/service: {{ $serviceName }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $registryConfig.registry $registryConfig.username $registryConfig.password (printf "%s:%s" $registryConfig.username $registryConfig.password | b64enc) | b64enc }}
{{- end }}