{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.gitea (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    resource.dependencies/deployments: "{{ include "common.names.custom" (list . "mirror") }} {{ include "common.names.custom" (list . "portal") }} {{ include "common.names.custom" (list . "proxy") }} {{ include "common.names.custom" (list . "server") }} {{ include "common.names.custom" (list . "user") }} {{ include "common.names.custom" . }}"
    {{- with $conf.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- $secretData := (lookup "v1" "Secret" .Release.Namespace (include "common.names.custom" .)).data }}
  {{- $user := "gitea" | b64enc }}
  {{- $password := randAlphaNum 15 | b64enc }}
  {{- $email := "gitea@example.com" | b64enc }}
  {{- if $secretData }}
  {{- $user = index $secretData "GITEA_ADMIN_USER" }}
  {{- $password = index $secretData "GITEA_ADMIN_PASSWORD" }}
  {{- $email = index $secretData "GITEA_ADMIN_EMAIL" }}
  {{- end }}
  GITEA_ADMIN_USER: {{ $user }}
  GITEA_ADMIN_PASSWORD: {{ $password }}
  GITEA_ADMIN_EMAIL: {{ $email }}
{{- end }}