kind: Service
apiVersion: v1
metadata:
  name: agent-sandbox-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app: agent-sandbox-controller
spec:
  selector:
    app: agent-sandbox-controller
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
