kind: ServiceAccount
apiVersion: v1
metadata:
  name: agent-sandbox-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app: agent-sandbox-controller
