{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if .Values.global.gitaly.enabled }}
{{- $service := include "common.service" (dict "service" "gitaly" "global" .) | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- if $service.labels }}
      {{- toYaml $service.labels | nindent 4 }}
    {{- else }}
      {{- include "common.labels" . | nindent 4 }}
    {{- end }}
  annotations:
    reloader.stakater.com/auto: "true"
    {{- if $service.annotations }}
      {{- toYaml $service.annotations | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ $service.replicas | default 1 }}
  serviceName: {{ $serviceName }}
  minReadySeconds: {{ $service.minReadySeconds | default 30 }}
  selector:
    matchLabels:
      app.kubernetes.io/service: {{ $service.name }}
      {{- if $service.selector }}
        {{- toYaml $service.selector | nindent 6 }}
      {{- else }}
        {{- include "common.labels.selector" . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/service: {{ $service.name }}
        {{- if $service.podLabels }}
          {{- toYaml $service.podLabels | nindent 8 }}
        {{- else }}
          {{- include "common.labels" . | nindent 8 }}
        {{- end }}
      annotations:
      {{- if $service.podAnnotations }}
        {{- toYaml $service.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ $service.terminationGracePeriodSeconds | default 20 }}
      {{- if $service.serviceAccountName }}
      serviceAccountName: {{ $service.serviceAccountName }}
      automountServiceAccountToken: {{ $service.automountServiceAccountToken | default true }}
      {{- end }}
      {{- with (or $service.image.pullSecrets .Values.global.image.pullSecrets) }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ $service.name }}
          image: {{ include "common.image" (list . $service.image) }}
          imagePullPolicy: {{ or $service.image.pullPolicy .Values.global.image.pullPolicy }}
          ports:
            - containerPort: 8075
              name: {{ $service.service.name | default $service.name }}
              protocol: {{ $service.service.protocol | default "TCP" }}
          {{- with $service.environments }}
          env:
          {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/opt/gitaly/repositories
            - name: config
              mountPath: /etc/gitaly
          {{- if $service.resources }}
          resources:
            {{- toYaml $service.resources | nindent 12 }}
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: 8075
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            exec:
              command: [ "/scripts/healthcheck" ]
            initialDelaySeconds: 10
            periodSeconds: 5
          {{- if $service.startupProbe }}
          startupProbe:
            {{- toYaml $service.startupProbe | nindent 12 }}
          {{- end }}
          {{- if $service.securityContext }}
          securityContext:
            {{- toYaml $service.securityContext | nindent 12 }}
          {{- end }}
          {{- if $service.lifecycle }}
          lifecycle:
            {{- toYaml $service.lifecycle | nindent 12 }}
          {{- end }}
          {{- if $service.stdin }}
          stdin: {{ $service.stdin }}
          {{- end }}
          {{- if $service.tty }}
          tty: {{ $service.tty }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ $serviceName }}
      {{- if $service.nodeSelector }}
      nodeSelector:
        {{- toYaml $service.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $service.tolerations }}
      tolerations:
        {{- toYaml $service.tolerations | nindent 8 }}
      {{- end }}
      {{- if $service.affinity }}
      affinity:
        {{- toYaml $service.affinity | nindent 8 }}
      {{- end }}
      {{- if $service.podSecurityContext }}
      securityContext:
        {{- toYaml $service.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if $service.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml $service.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if $service.hostname }}
      hostname: {{ $service.hostname }}
      {{- end }}
      {{- if $service.subdomain }}
      subdomain: {{ $service.subdomain }}
      {{- end }}
  {{- $persistence := $service.persistence }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        namespace: {{ .Release.Namespace }}
        labels:
          app.kubernetes.io/service: {{ $service.name }}
          {{- include "common.labels" . | nindent 10 }}
        annotations:
          helm.sh/resource-policy: keep
          {{- if $persistence.annotations }}
            {{- toYaml $persistence.annotations | nindent 10 }}
          {{- end }}
      spec:
        accessModes:
        {{- range $mode := (or $persistence.accessModes .Values.global.persistence.accessModes) }}
          - {{ $mode | default "ReadWriteOnce" }}
        {{- end }}
        {{- with (or $persistence.storageClass .Values.global.persistence.storageClass) }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ or $persistence.size .Values.global.persistence.size }}
  {{- if $service.updateStrategy }}
  updateStrategy:
    {{- toYaml $service.updateStrategy | nindent 4 }}
  {{- end }}
  {{- if $service.podManagementPolicy }}
  podManagementPolicy: {{ $service.podManagementPolicy }}
  {{- end }}
  {{- if $service.revisionHistoryLimit }}
  revisionHistoryLimit: {{ $service.revisionHistoryLimit }}
  {{- end }}
{{- end }}
