kind: Deployment
apiVersion: apps/v1
metadata:
  name: agent-sandbox-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app: agent-sandbox-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-sandbox-controller
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app: agent-sandbox-controller
    spec:
      serviceAccountName: agent-sandbox-controller
      containers:
      - name: agent-sandbox-controller
        image: {{ include "common.image" (list . .Values.image) | replace "docker.io" "registry.k8s.io" }}
        args:
        - "--leader-elect=true"
        - "--extensions"
        ports:
        - name: metrics
          containerPort: 8080
          protocol: TCP
        - name: healthz
          containerPort: 8081
          protocol: TCP
