{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.global.deploy.enabled }}
{{- $objectStoreConfig := include "chart.objectStoreConfig" (dict "service" .Values.csghub.runner "global" .) | fromYaml }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.custom" (list . "runner") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "runner") | nindent 4 }}
  annotations: {{ .Values.csghub.runner.annotations | toYaml | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "runner") | nindent 6 }}
  replicas: {{ .Values.csghub.runner.replicas }}
  revisionHistoryLimit: 1
  minReadySeconds: 30
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/services/runner/configmap.yaml") . | sha256sum }}
        {{- with .Values.csghub.runner.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels" (dict "context" . "service" "runner") | nindent 8 }}
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - {{ include "coredns.csghub" . }}
        searches:
          - {{ .Release.Namespace }}.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
      {{- with (or .Values.global.image.pullSecrets .Values.csghub.runner.image.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.csghub.runner.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.csghub.runner.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.custom" (list . "runner")}}
      automountServiceAccountToken: {{ .Values.csghub.runner.serviceAccount.automount }}
      {{- end }}
      initContainers:
        - name: wait-for-server
          image: {{ or .Values.global.image.registry .Values.csghub.runner.image.registry }}/busybox:latest
          imagePullPolicy: {{ .Values.csghub.runner.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until nc -z {{ include "server.internal.domain" . }} {{ include "server.internal.port" . }}; do echo 'Wait for csghub-server to be ready'; sleep 2; done" ]
      containers:
        - name: runner
          image: {{ or .Values.global.image.registry .Values.csghub.runner.image.registry }}/{{ or .Values.global.image.name .Values.csghub.runner.image.repository }}:{{ include "csghub.image.tag" (dict "tag" (or .Values.global.image.tag .Values.csghub.runner.image.tag) "context" .) }}
          imagePullPolicy: {{ or .Values.global.image.pullPolicy .Values.csghub.runner.image.pullPolicy }}
          command: [ "/starhub-bin/starhub", "deploy", "runner" ]
          ports:
            - containerPort: 8082
              name: runner
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" (list . "runner") }}
            - configMapRef:
                name: {{ include "common.names.custom" (list . "server") }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "nats") }}
          env:
            - name: STARHUB_SERVER_DOCKER_REG_BASE
              value: {{ printf "%s/%s" (include "csghub.registry.repository" .) (include "csghub.registry.namespace" .) }}
            - name: STARHUB_SERVER_DOCKER_IMAGE_PULL_SECRET
              value: {{ include "common.names.custom" (list . "registry-docker-config") }}
            - name: OPENCSG_ACCOUNTING_NATS_URL
              value: "nats://$(NATS_USERNAME):$(NATS_PASSWORD)@{{ include "nats.internal.domain" . }}:{{ include "nats.internal.ports.api" . }}"
            - name: STARHUB_SERVER_ARGO_S3_PUBLIC_BUCKET
              value: {{ $objectStoreConfig.bucket }}
            {{- if .Values.global.objectStore.enabled }}
            - name: STARHUB_SERVER_S3_ACCESS_KEY_ID
              value: "$(MINIO_ROOT_USER)"
            - name: STARHUB_SERVER_S3_ACCESS_KEY_SECRET
              value: "$(MINIO_ROOT_PASSWORD)"
            {{- end }}
            {{- with .Values.csghub.runner.environments }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- .Values.csghub.runner.resources | toYaml | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          securityContext:
            {{- .Values.csghub.runner.podSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: kube-configs
              mountPath: /root/.kube
              readOnly: true
      volumes:
        - name: kube-configs
          secret:
            {{- $secret := or .Values.global.deploy.kubeSecret .Values.csghub.runner.deployment.kubeSecret }}
            {{- $exists := lookup "v1" "Secret" .Release.Namespace $secret }}
            {{- if $exists }}
            secretName: {{ $secret }}
            {{- end }}
      {{- with .Values.csghub.runner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.csghub.runner.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.csghub.runner.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
