{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.global.deploy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "runner") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "runner") | nindent 4 }}
spec:
  type: {{ .Values.csghub.runner.service.type }}
  ports:
    - port: {{ .Values.csghub.runner.service.port }}
      targetPort: 8082
      protocol: TCP
      name: runner
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "runner") | nindent 4 }}
{{- end }}