{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.redis (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    resource.dependencies/deployments: "{{ include "common.names.custom" (list . "server") }} {{ include "common.names.custom" (list . "mirror") }}"
    resource.dependencies/statefulsets: "{{ include "common.names.custom" . }} {{ include "common.names.custom" (list . "builder") }}"
    {{- with $conf.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  REDIS_HOST: {{ include "common.names.custom" . | quote }}
  REDIS_PORT: {{ $conf.service.port | quote }}
  REDIS_ENDPOINT: {{ include "redis.internal.endpoint" . | trimPrefix "http://" }}
{{- end }}