{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.nats (omit .Values "global" "exports") }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace (include "common.names.custom" .)).data -}}
{{- $username := "natsadmin" -}}
{{- $password := randAlphaNum 15 -}}
{{- if $secretData }}
{{- $username = index $secretData "NATS_USERNAME" | b64dec -}}
{{- $password = index $secretData "NATS_PASSWORD" | b64dec -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with $conf.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  NATS_USERNAME: {{ $username | b64enc }}
  NATS_PASSWORD: {{ $password | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    resource.dependencies/deployments: "{{ include "common.names.custom" (list . "server") }} {{ include "common.names.custom" (list . "user") }} {{ include "common.names.custom" (list . "portal") }} {{ include "common.names.custom" (list . "accounting") }} {{ include "common.names.custom" (list . "runner") }} {{ include "common.names.custom" (list . "proxy") }}"
    resource.dependencies/statefulsets: "{{ include "common.names.custom" . }}"
    {{- with $conf.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  nats-server.conf: |
    debug = true
    trace = true

    # Client port of 4222 on all interfaces
    port: 4222

    # HTTP monitoring port
    monitor_port: 8222

    jetstream: enabled

    jetstream {
      store_dir: /data/jetstream
      max_mem: 8G
      max_file: 10G
    }

    authorization {
      ADMIN = {
        publish = ">"
        subscribe = ">"
    }

    users = [
        { user: {{ $username | quote }}, password: {{ htpasswd $username $password | trimPrefix (printf "%s:" $username) }}, permissions: $ADMIN }
      ]
    }