{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "user") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "user") | nindent 4 }}
spec:
  type: {{ .Values.csghub.user.service.type }}
  ports:
    - port: {{ .Values.csghub.user.service.port }}
      targetPort: 8080
      protocol: TCP
      name: user
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true  "context" . "service" "user") | nindent 4 }}