{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.api }}
      targetPort: 4222
      protocol: TCP
      name: api
    - port: {{ .Values.service.ports.cluster }}
      targetPort: 6222
      protocol: TCP
      name: cluster
    - port: {{ .Values.service.ports.monitor }}
      targetPort: 8222
      protocol: TCP
      name: monitor
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
