{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $pgConfig := include "csghub.postgresql.config" (dict "service" .Values "global" .) | fromYaml }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 10
  activeDeadlineSeconds: 1200
  template:
    metadata:
      name: {{ include "common.names.custom" . }}
      labels: {{ include "common.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- with (or .Values.image.pullSecrets .Values.global.image.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      initContainers:
        - name: wait-for-postgresql
          image: {{ include "image.fixed.prefix" (list . "opencsghq/psql:latest")  }}
          imagePullPolicy: {{ or .Values.image.pullPolicy .Values.global.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until psql \"{{ include "csghub.postgresql.dsn" (dict "service" .Values "global" .) }}\" -c 'SELECT 1'; do echo 'Wait for PostgreSQL to be ready'; sleep 2; done" ]
        - name: wait-for-server
          image: {{ include "image.fixed.prefix" (list . "busybox:latest")  }}
          imagePullPolicy: {{ or .Values.image.pullPolicy .Values.global.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until nc -z {{ include "common.names.custom" (list . "server") }} {{ include "csghub.svc.port" "server" }}; do echo 'Wait for csghub-server to be ready'; sleep 2; done" ]
      containers:
        - name: psql
          image: {{ include "image.fixed.prefix" (list . "opencsghq/psql:latest")  }}
          imagePullPolicy: {{ or .Values.image.pullPolicy .Values.global.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "for sql_file in /scripts/*.sql; do echo Executing $$sql_file; psql -f $$sql_file; done" ]
          env:
            - name: PGHOST
              value: {{ $pgConfig.host }}
            - name: PGPORT
              value: {{ $pgConfig.port | quote }}
            - name: PGDATABASE
              value: {{ $pgConfig.database }}
            - name: PGUSER
              value: {{ $pgConfig.user }}
            - name: PGPASSWORD
              value: {{ $pgConfig.password }}
          volumeMounts:
            - name: init
              mountPath: /scripts
      volumes:
        - name: init
          configMap:
            name: {{ include "common.names.custom" (list . "casdoor-init") }}
