{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if .Values.global.mongo.enabled }}
{{- $mongoConfig := include "csghub.mongo.config" (dict "service" .Values "global" .) | fromYaml }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "mongo") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ $mongoConfig.port }}
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
{{- end }}
