{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/ -}}

{{- if .Values.superset.enabled }}
{{- $secretName := include "common.names.custom" (list . "superset-env") }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $existingKey := "" }}
{{- if $existingSecret }}
{{- $existingKey = (($existingSecret.data).SUPERSET_SECRET_KEY) }}
{{- end }}
{{- $casdoorEndpoint := include "common.endpoint.casdoor" . }}
{{- $casdoorApp := include "csghub.casdoor.client" "Superset" | fromYaml }}
{{- $existingData := (lookup "v1" "Secret" .Release.Namespace $secretName).data | default dict }}
{{- $supersetSvc := dict "name" "superset" "postgresql" (dict "database" "csghub_superset") }}
{{- $pgConfig := include "common.postgresql.config" (dict "ctx" . "service" $supersetSvc) | fromYaml }}
{{- $redisConfig := include "common.redis.config" (dict "ctx" . "service" (dict)) | fromYaml }}
{{- $casdoorSvc := include "common.service" (dict "ctx" . "service" "casdoor") | fromYaml }}
{{- $casdoorInitSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-init" (include "common.names.custom" (list . $casdoorSvc.name))) }}
{{- $adminPass := $casdoorSvc.admin.password | default (include "common.randomPassword" $casdoorSvc.name) }}
{{- if $casdoorInitSecret }}
{{- $adminPass = (($casdoorInitSecret.data).INIT_ADMIN_PASSWORD) | b64dec | default $adminPass }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  SUPERSET_SECRET_KEY: {{ $existingKey | default (randAlphaNum 56 | b64enc) | quote }}
  ADMIN_PASSWORD: {{ $adminPass | b64enc | quote }}
  CASDOOR_ENDPOINT: {{ $casdoorEndpoint | b64enc | quote }}
  CASDOOR_CLIENT_ID: {{ dig "CASDOOR_CLIENT_ID" ($casdoorApp.clientId | b64enc) $existingData | quote }}
  CASDOOR_CLIENT_SECRET: {{ dig "CASDOOR_CLIENT_SECRET" ($casdoorApp.clientSecret | b64enc) $existingData | quote }}
  DB_HOST: {{ $pgConfig.host | b64enc | quote }}
  DB_PORT: {{ $pgConfig.port | toString | b64enc | quote }}
  DB_USER: {{ $pgConfig.user | b64enc | quote }}
  DB_PASS: {{ $pgConfig.password | b64enc | quote }}
  DB_NAME: {{ $pgConfig.database | b64enc | quote }}
  REDIS_HOST: {{ $redisConfig.host | b64enc | quote }}
  REDIS_PORT: {{ $redisConfig.port | toString | b64enc | quote }}
{{- if or (and .Values.global.redis.enabled .Values.redis.requirePass) (and (not .Values.global.redis.enabled) $redisConfig.password) }}
  REDIS_PASSWORD: {{ $redisConfig.password | b64enc | quote }}
{{- end }}
{{- end }}
