{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.registry (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    resource.dependencies/statefulsets: "{{ include "common.names.custom" . }}"
    {{- with $conf.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  REGISTRY_AUTH: "htpasswd"
  REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
  REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
  REGISTRY_STORAGE: s3
  {{- if .Values.global.minio.enabled }}
  {{- if .Values.global.ingress.tls.enabled }}
  REGISTRY_STORAGE_S3_ENCRYPT: "true"
  REGISTRY_STORAGE_S3_SECURE: "true"
  {{- else }}
  REGISTRY_STORAGE_S3_ENCRYPT: "false"
  REGISTRY_STORAGE_S3_SECURE: "false"
  {{- end }}
  REGISTRY_STORAGE_S3_SECURE: "false"
  REGISTRY_STORAGE_S3_REGIONENDPOINT: {{ include "minio.internal.endpoint" . }} # used to generate download links for lfs files
  REGISTRY_STORAGE_S3_BUCKET: "csghub-git"
  REGISTRY_STORAGE_S3_REGION: "cn-north-1"
  REGISTRY_STORAGE_S3_FORCEPATHSTYLE: "true"
  {{- else }}
  {{- with $conf.objectStore }}
  REGISTRY_STORAGE_S3_REGIONENDPOINT: {{ .endpoint }}
  REGISTRY_STORAGE_S3_ACCESSKEY: {{ .accessKey }}
  REGISTRY_STORAGE_S3_SECRETKEY: {{ .accessSecret }}
  REGISTRY_STORAGE_S3_BUCKET: {{ .bucket }}
  REGISTRY_STORAGE_S3_REGION: {{ .region }}
  REGISTRY_STORAGE_S3_ENCRYPT: {{ .encrypt }}
  REGISTRY_STORAGE_S3_SECURE: {{ .secure }}
  REGISTRY_STORAGE_S3_FORCEPATHSTYLE: {{ .pathStyle }}
  {{- end }}
  {{- end }}
{{- end }}