{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.registry (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels.selector" . | nindent 6 }}
  serviceName: {{ include "common.names.custom" . }}
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with $conf.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      {{- with (or $conf.imagePullSecrets .Values.global.imagePullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with $conf.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if $conf.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.custom" . }}
      automountServiceAccountToken: {{ $conf.serviceAccount.automount }}
      {{- end }}
      containers:
        - name: registry
          image: {{ $conf.image.repository }}:{{ .Values.global.registry.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ $conf.image.pullPolicy }}
          ports:
            - containerPort: 5000
              name: registry
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" . }}
            {{- if .Values.global.minio.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "minio") }}
            {{- end }}
          env:
          {{- if $conf.ingress.tls.enabled }}
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/opt/certs/x509/tls.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/opt/certs/x509/tls.key"
          {{- end }}
          {{- if .Values.global.minio.enabled }}
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              value: "$(MINIO_ROOT_USER)"
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              value: "$(MINIO_ROOT_PASSWORD)"
          {{- end }}
          {{- with $conf.environments }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          resources:
            {{- $conf.resources | toYaml | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            {{- $conf.podSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: auth
              mountPath: /auth
            - name: data
              mountPath: /var/lib/registry
            {{- if $conf.ingress.tls.enabled }}
            - name: certs
              mountPath: /opt/certs/x509
            {{- end }}
      volumes:
        - name: auth
          secret:
            secretName: {{ include  "common.names.custom" . }}
            items:
              - key: htpasswd
                path: htpasswd
        {{- if $conf.ingress.tls.enabled }}
        - name: certs
          secret:
            {{- if $conf.ingress.tls.secretName }}
            secretName: {{ $conf.ingress.tls.secretName }}
            {{- else }}
            secretName: {{ include "common.names.custom" (list . "certs") }}
            {{- end }}
        {{- end }}
      {{- with $conf.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $conf.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $conf.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        namespace: {{ .Release.Namespace }}
        labels:
          {{- include "common.labels" . | nindent 10 }}
        annotations:
          helm.sh/resource-policy: keep
          {{- with $conf.annotations }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        accessModes: {{ $conf.persistence.accessMode }}
        {{- if $conf.persistence.storageClass }}
        storageClassName: {{ $conf.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ $conf.persistence.size }}
{{- end }}