{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
data:
  initialize.sh: |
    #!/bin/bash
    set -eu
    # Create alias
    ALIAS="myMinio"
    {{ printf "mc alias set $ALIAS %s $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD" (include "minio.internal.endpoint" .) }}

    # Apply region
    {{- $REGION := .Values.region | default "cn-north-1" }}
    mc admin config set "$ALIAS" region name={{ $REGION }}
    mc admin service restart "$ALIAS" --quiet

    set +e
    # Create buckets
    {{- range $BUCKET := .Values.buckets.defaults }}
    if mc ls $ALIAS/{{ $BUCKET }} &>/dev/null; then
      echo "Bucket \`$ALIAS/{{ $BUCKET }}\` already exists."
    else
      # Assemble the command for bucket creation
      {{- printf "mc mb --region=%s $ALIAS/%s" $REGION $BUCKET | nindent 6 }}
    fi
    {{- end }}
{{- end }}