{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.ports.api }}
      targetPort: 9000
      protocol: TCP
      name: api
    - port: {{ add .Values.service.ports.console }}
      targetPort: 9001
      protocol: TCP
      name: console
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
{{- end }}