{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.enabled }}
{{- $pgConfig := include "csghub.postgresql.config" (dict "service" .Values "global" .) | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    resource.dependencies/deployments: |
      {{ include "common.names.custom" . }}
data:
  DB: "postgres12"
  DEFAULT_NAMESPACE_RETENTION: "7d"
  DBNAME: {{ $pgConfig.database }}
  DB_PORT: {{ $pgConfig.port | quote }}
  POSTGRES_SEEDS: {{ $pgConfig.host }}
  POSTGRES_USER: {{ $pgConfig.user }}
  POSTGRES_PWD: {{ $pgConfig.password }}
  VISIBILITY_DBNAME: {{ printf "%s_visibility" $pgConfig.database }}
{{- end }}