{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    resource.dependencies/deployments: >
      {{ include "common.names.custom" . }}
data:
  DB: "postgres12"
  DEFAULT_NAMESPACE_RETENTION: "7d"
  {{- if not .Values.global.postgresql.external }}
  DBNAME: "csghub_temporal"
  DB_PORT: {{ include "postgresql.internal.port" . | quote }}
  POSTGRES_SEEDS: {{ include "postgresql.internal.domain" . }}
  POSTGRES_USER: "csghub_temporal"
  VISIBILITY_DBNAME: "csghub_temporal_visibility"
  {{- else }}
  {{- with .Values.global.postgresql }}
  DBNAME: {{ .database }}
  DB_PORT: {{ .port | quote }}
  POSTGRES_SEEDS: {{ .host }}
  POSTGRES_USER: {{ .username }}
  POSTGRES_PWD: {{ .password }}
  VISIBILITY_DBNAME: {{ printf "%s_visibility" .database }}
  {{- end }}
  {{- end }}
{{- end }}