{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "ctx" . "service" "agenticflow") | fromYaml }}
{{- $agenticflowName := include "common.names.custom" (list . $service.name) }}
{{- $serviceName := include "common.names.custom" (list . "template-importer") }}
{{- if ne .Values.global.edition "ce" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: template-importer
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "10"
spec:
  activeDeadlineSeconds: 3600
  backoffLimit: 10
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/service: template-importer
        {{- include "common.labels" . | nindent 8 }}
    spec:
      restartPolicy: "OnFailure"
      terminationGracePeriodSeconds: 30
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
{{- end }}
      containers:
        - name: importer
          image: {{ include "common.image.fixed" (dict "ctx" . "service" "agenticflow" "image" "opencsghq/agenticflow-importer:latest") }}
          imagePullPolicy: {{ or $service.image.pullPolicy .Values.global.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ $agenticflowName }}
          {{- with $service.environments }}
          env:
          {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if $service.resources }}
          resources:
            {{- toYaml $service.resources | nindent 12 }}
          {{- end }}
          {{- if $service.securityContext }}
          securityContext:
            {{- toYaml $service.securityContext | nindent 12 }}
          {{- end }}
      {{- if $service.nodeSelector }}
      nodeSelector:
        {{- toYaml $service.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $service.tolerations }}
      tolerations:
        {{- toYaml $service.tolerations | nindent 8 }}
      {{- end }}
      {{- if $service.affinity }}
      affinity:
        {{- toYaml $service.affinity | nindent 8 }}
      {{- end }}
