{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.temporal (omit .Values "global" "exports") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
spec:
  type: {{ $conf.service.type }}
  ports:
    - port: {{ $conf.service.port }}
      targetPort: 7233
      protocol: TCP
      name: temporal
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: temporal-ui
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}