apiVersion: v2
name: runner
description: Responsible for deploying and managing application instances in the Kubernetes cluster to
  ensure fast building and continuous delivery of applications.
home: https://opencsg.com
icon: https://raw.githubusercontent.com/OpenCSGs/csghub-charts/main/icons/icon.png
sources:
  - https://github.com/OpenCSGs/csghub-charts

maintainers:
  - name: OpenCSG Team
    email: support@opencsg.com
    url: https://opencsg.com

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.3.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: v2.3.0

# Defined dependencies for subChart
dependencies:
  - name: common
    version: 0.2.2
    repository: https://charts.opencsg.com/csghub
  - name: reloader
    version: 2.2.14
    repository: https://charts.opencsg.com/infra
    condition: reloader.enabled
    tags:
      - dependencies
      - reloader
  - name: prometheus
    version: 29.14.0
    repository: https://charts.opencsg.com/infra
    condition: prometheus.enabled
    tags:
      - dependencies
      - monitor
  - name: gateway-helm
    alias: envoy
    version: 1.7.5
    repository: oci://docker.io/envoyproxy
    condition: envoy.enabled
    tags:
      - dependencies
      - gateway
  - name: lws
    version: v0.6.1
    repository: https://charts.opencsg.com/infra
    condition: lws.enabled
  - name: argo-workflows
    alias: argo
    version: 0.47.5
    repository: https://charts.opencsg.com/infra
    condition: argo.enabled
  - name: knative-operator
    alias: knative
    version: 1.22.1
    repository: https://charts.opencsg.com/infra
    condition: knative.enabled
  - name: volcano
    version: 1.14.3
    repository: https://charts.opencsg.com/infra
    condition: volcano.enabled
  - name: agent-sandbox
    version: 0.4.6
    repository: https://charts.opencsg.com/csghub
    condition: agent-sandbox.enabled
