{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if and (ne .Values.global.edition "ce") (not .Values.global.chartContext.isBuiltIn) }}
{{- $gateway := .Values.global.gateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: csghub-gateway
spec:
  controllerName: {{ $gateway.controllerName }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: listeners
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: csghub-gateway
  {{- if regexMatch "envoyproxy" .Values.global.gateway.controllerName }}
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: {{ include "common.names.custom" (list . "envoy-proxy") }}
  {{- end }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    {{- if $gateway.tls.enabled }}
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: {{ $gateway.tls.secretName }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
{{- end }}
