{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if and (not .Values.global.chartContext.isBuiltIn) .Values.global.gateway.tls.enabled }}
{{- $service := include "common.service" (dict "ctx" . "service" "agenticflow") | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-redirect" $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- if $service.labels }}
      {{- toYaml $service.labels | nindent 4 }}
    {{- else }}
      {{- include "common.labels" . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
    - name: listeners
      sectionName: http
  hostnames:
    - {{ include "common.domain.agenticflow" . }}
  rules:
      - filters:
          - type: RequestRedirect
            requestRedirect:
              scheme: https
              statusCode: 301
---
{{- $csgbotSvc := include "common.service" (dict "ctx" . "service" "csgbot") | fromYaml }}
{{- $csgbotSvcName := include "common.names.custom" (list . $csgbotSvc.name) }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-redirect" $csgbotSvcName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $csgbotSvc.name }}
    {{- if $csgbotSvc.labels }}
      {{- toYaml $csgbotSvc.labels | nindent 4 }}
    {{- else }}
      {{- include "common.labels" . | nindent 4 }}
    {{- end }}
spec:
  parentRefs:
    - name: listeners
      sectionName: http
  hostnames:
    - {{ include "common.domain.csgbot" . }}
  rules:
      - filters:
          - type: RequestRedirect
            requestRedirect:
              scheme: https
              statusCode: 301
{{- end }}
