{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
data:
  wait-for-ready.sh: |
    #!/usr/bin/env bash
    while true; do
      if [[ $(kubectl get pods -n {{ .Release.Namespace }} -o jsonpath='{.items[?(@.status.phase!="Running")].metadata.name}' | grep -v "$HOSTNAME") ]]; then
        echo "Not all pods are running yet. Waiting..."
        sleep 5
      else
        break
      fi
    done
{{- end }}