{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if and .Values.global.postgresql.enabled (not .Values.chartContext.isBuiltIn) }}
{{- $secretName := include "common.names.custom" (list . "postgresql") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
{{- $processed := dict -}}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace $secretName).data }}
{{- range $dbName, $dbConfig := .Values.postgresql.databases }}
{{- $username := $dbConfig.owner }}
{{- if not (hasKey $processed $username )}}
{{- $password := $dbConfig.password | default (include "common.randomPassword" $username) | b64enc }}
{{- if and $secretData (index $secretData $username) }}
{{- $password = index $secretData $username }}
{{- end }}
{{- if and $username $password }}
  {{ $username }}: {{ $password }}
{{- $_ := set $processed $username true }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
