{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if and .Values.global.postgresql.enabled (not .Values.chartContext.isBuiltIn) }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.custom" (list . "postgresql") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
    {{- with .Values.postgresql.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels.selector" . | nindent 6 }}
  serviceName: {{ include "common.names.custom" (list . "postgresql") }}
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      annotations:
        {{- with .Values.postgresql.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      {{- with (or .Values.postgresql.image.pullSecrets .Values.image.pullSecrets .Values.global.image.pullSecrets) }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .Values.postgresql.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgresql
          image: {{ include "image.generic.prefix" (list . .Values.postgresql.image) }}
          imagePullPolicy: {{ or .Values.postgresql.image.pullPolicy .Values.image.pullPolicy .Values.global.image.pullPolicy }}
          args: [ "-c", "config_file=/etc/postgresql/postgresql.conf" ]
          ports:
            - containerPort: 5432
              name: postgresql
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" (list . "postgresql") }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "common.names.custom" (list . "postgresql") }}
                  key: postgres
            {{- with .Values.postgresql.environments }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- .Values.postgresql.resources | toYaml | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "postgres", "-h", "127.0.0.1", "-p", "5432"]
          securityContext:
            {{- .Values.postgresql.podSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /etc/postgresql
      volumes:
        - name: config
          configMap:
            name: {{ include "common.names.custom" (list . "postgresql") }}
      {{- with .Values.postgresql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        namespace: {{ .Release.Namespace }}
        labels:
          {{- include "common.labels" . | nindent 10 }}
        annotations:
          helm.sh/resource-policy: keep
          {{- with .Values.postgresql.annotations }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        accessModes: {{ or .Values.postgresql.persistence.accessMode .Values.global.persistence.accessMode }}
        {{- if (or .Values.postgresql.persistence.storageClass .Values.global.persistence.storageClass) }}
        storageClassName: {{ or .Values.postgresql.persistence.storageClass .Values.global.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ or .Values.postgresql.persistence.size .Values.global.persistence.size }}
{{- end }}
