{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.csghub.dataviewer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "dataviewer") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "dataviewer") | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.csghub.dataviewer.service.port }}
      targetPort: 8093
      protocol: TCP
      name: dataviewer
  selector:
    {{- include "common.labels" (dict "context" . "service" "dataviewer") | nindent 4 }}
{{- end }}