# Example values file for Enterprise Edition (EE) deployment
# This configuration will deploy CSGHub EE with Starship components

global:
  # Set edition to EE
  edition: "ee"
  
  image:
    #registry: "opencsg-registry.cn-beijing.cr.aliyuncs.com"
    # Base tag without suffix - will become v1.8.0-ee automatically
    tag: "v1.8.0"
    pullPolicy: "IfNotPresent"

  ingress:
    domain: "csghub-ee.example.com"
    tls:
      enabled: false

  # External services configuration (optional)
  postgresql:
    enabled: true
  
  redis:
    enabled: true
  
  objectStore:
    enabled: true

  # Starship OAuth configuration (for EE)
  starship:
    oauth:
      issuer: "https://gitlab.example.com"
      clientId: "your-client-id"
      clientSecret: "your-client-secret"

# Starship configuration - explicitly enable for EE
starship:
  # Must be explicitly set to true for Starship to be deployed
  enabled: true

  # Starship-specific configurations
  web:
    openai:
      model: "gpt-4"
      api:
        base: "https://api.openai.com/v1"
        version: "2024-06-01"
        key: ""  # Set via environment variable or secret

    persistence:
      size: 10Gi
      accessMode: ["ReadWriteMany"]

# Resource configurations
postgresql:
  persistence:
    size: 50Gi

minio:
  persistence:
    size: 100Gi

gitaly:
  persistence:
    size: 200Gi

# Csghub Component-specific configurations
csghub:
  server:
    replicas: 1

  portal:
    replicas: 1

