# Example values file for Community Edition (CE) deployment
# This configuration will deploy CSGHub CE without Starship components

global:
  # Set edition to CE
  edition: "ce"
  
  image:
    #registry: "opencsg-registry.cn-beijing.cr.aliyuncs.com"
    # Base tag without suffix - will become v1.8.0-ce automatically
    tag: "v1.8.0"
    pullPolicy: "IfNotPresent"

  ingress:
    domain: "csghub-ce.example.com"
    tls:
      enabled: false

  # External services configuration (optional)
  postgresql:
    enabled: true
  
  redis:
    enabled: true
  
  objectStore:
    enabled: true

# Starship configuration - will be ignored in CE edition
starship:
  # This setting will be ignored since global.edition is "ce"
  enabled: true

# Resource configurations
postgresql:
  persistence:
    size: 50Gi

minio:
  persistence:
    size: 100Gi

gitaly:
  persistence:
    size: 200Gi

# Component-specific configurations
csghub:
  server:
    replicas: 1

  portal:
    replicas: 1

