# Example values file for Enterprise Edition (EE) deployment WITHOUT Csgship
# This configuration will deploy CSGHub EE but disable Csgship components

global:
  # Set edition to EE
  edition: "ee"

  image:
    #registry: "opencsg-registry.cn-beijing.cr.aliyuncs.com"
    # Base tag without suffix - will become v1.8.0-ee automatically
    tag: "v1.8.0"
    pullPolicy: "IfNotPresent"

  ingress:
    domain: "csghub-ee-no-csgship.example.com"
    tls:
      enabled: false

  # External services configuration (optional)
  postgresql:
    enabled: true

  redis:
    enabled: true

  objectStore:
    enabled: true

# Resource configurations
postgresql:
  persistence:
    size: 50Gi

minio:
  persistence:
    size: 100Gi

gitaly:
  persistence:
    size: 200Gi


# Csgship configuration - explicitly disable even in EE
csgship:
  # Set to false to disable Csgship even in EE edition
  enabled: false

# Csghub Component-specific configurations
csghub:
  server:
    replicas: 1

  portal:
    replicas: 1
