{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "service" "labelStudio" "global" .) | fromYaml }}
{{- $dataflowSvc := include "common.service" (dict "service" "dataflow" "global" .) | fromYaml }}
{{- $ingressConfig := include "common.ingress.config" (dict "service" $service "global" .) | fromYaml }}
{{- if and $ingressConfig.enabled (not .Values.global.chartContext.isBuiltIn) }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- $labelStudioPort := dig "service" "port" 8002 $service }}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- if $service.labels }}
      {{- toYaml $service.labels | nindent 4 }}
    {{- else }}
      {{- include "common.labels" . | nindent 4 }}
    {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    {{- if .Values.global.chartContext.isBuiltIn }}
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ include "common.endpoint.csghub" . | quote }}
    {{- else }}
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.externalUrl | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/custom-http-errors: "404,502,503"
    nginx.ingress.kubernetes.io/proxy_intercept_errors: "on"
    nginx.ingress.kubernetes.io/default-backend: {{ include "common.names.custom" (list . "ingress-nginx-defaultbackend") }}
    {{- if $service.annotations }}
      {{- toYaml $service.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className | default "nginx" }}
  {{- if $ingressConfig.tls.enabled }}
  tls:
    - hosts:
        - {{ include "common.domain.labelstudio" . }}
      secretName: {{ $ingressConfig.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ include "common.domain.labelstudio" . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
            {{- if eq (include "common.capabilities.ingress.apiVersion" .) "networking.k8s.io/v1" }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $labelStudioPort }}
            {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $labelStudioPort }}
            {{- end }}
{{- end }}
