{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.global.deployment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    resource.dependencies/deployments: |
      {{ include "common.names.custom" . }}
data:
  # Object Storage Connection Info
  STARHUB_SERVER_S3_ENABLE_SSL: {{ include "csghub.objectStore.encrypt" . | quote }}
  STARHUB_SERVER_S3_ENDPOINT: {{ include "csghub.objectStore.endpoint" . | trimPrefix "http://" | trimPrefix "https://" }}
  STARHUB_SERVER_S3_ACCESS_KEY_ID: {{ include "csghub.objectStore.accessKey" . }}
  STARHUB_SERVER_S3_ACCESS_KEY_SECRET: {{ include "csghub.objectStore.accessSecret" . }}
  STARHUB_SERVER_S3_BUCKET: {{ include "csghub.objectStore.bucket" . }}
  STARHUB_SERVER_ARGO_S3_PUBLIC_BUCKET: {{ include "csghub.objectStore.bucket" . }}
  STARHUB_SERVER_S3_REGION: {{ include "csghub.objectStore.region" . }}
  {{- if eq (include "csghub.objectStore.pathStyle" .) "true" }}
  STARHUB_SERVER_S3_BUCKET_LOOKUP: "true"
  {{- else }}
  STARHUB_SERVER_S3_BUCKET_LOOKUP: "auto"
  {{- end }}
{{- end }}