{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.global.deploy.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.deploy.namespace }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.global.deploy.namespace }}
    helm.sh/resource-policy: keep
    {{ include "common.labels" . | nindent 4 }}
{{- if not .Values.global.deploy.mergingNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.deploy.imageBuilder.namespace }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.global.deploy.imageBuilder.namespace }}
    helm.sh/resource-policy: keep
    {{ include "common.labels" . | nindent 4 }}
{{- end }}
{{- end }}