{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.builder (omit .Values "global" "exports") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    resource.dependencies/deployments: "{{ include "common.names.custom" (list . "runner") }} {{ include "common.names.custom" . }}"
    {{- with $conf.annotations }}
      {{- . | toYaml | nindent 4 }}
    {{- end }}
data:
  {{- if .Values.global.redis.enabled }}
  REDIS_ENDPOINT: {{ include "redis.internal.endpoint" . }}
  {{- else }}
  REDIS_ENDPOINT: {{ printf "%s:%s" $conf.redis.host ($conf.redis.port | toString) }}
  REDIS_HOST: {{ $conf.redis.host }}
  REDIS_PORT: {{ $conf.redis.port | toString }}
  REDIS_PASSWD: {{ $conf.redis.password }}
  {{- end }}
  SPACE_DATA_PATH: "/opt/data"
  {{- if .Values.global.registry.enabled }}
  REGISTRY_ADDRESS: {{ include "registry.external.endpoint" . | trimPrefix "http://" | trimPrefix "https://" }}
  REGISTRY_NAMESPACE: {{ .Values.global.registry.namespace }}
  {{- else }}
  {{- with $conf.registry }}
  REGISTRY_ADDRESS: {{ .repository | trimPrefix "http://" | trimPrefix "https://" }}
  REGISTRY_NAMESPACE: {{ .namespace }}
  REGISTRY_USERNAME: {{ .username }}
  REGISTRY_PASSWORD: {{ .password }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" (list . "builder-docker-daemon") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
data:
  daemon.json: |
    {
      "insecure-registries": [
        {{- if .Values.global.registry.enabled }}
        "{{ include "registry.external.endpoint" . | trimPrefix  "http://" | trimPrefix  "https://" }}"
        {{- else }}
        "{{ $conf.registry.repository }}"
        {{- end }}
      ]
    }
