{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if .Values.global.objectStore.enabled }}
{{- $service := include "common.service" (dict "service" "minio" "global" .) | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- if $service.labels }}
      {{- toYaml $service.labels | nindent 4 }}
    {{- else }}
      {{- include "common.labels" . | nindent 4 }}
    {{- end }}
  annotations:
    reloader.stakater.com/auto: "true"
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
    {{- if $service.annotations }}
      {{- toYaml $service.annotations | nindent 4 }}
    {{- end }}
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1200
  backoffLimit: 5
  ttlSecondsAfterFinished: 600
  completionMode: "Indexed"
  template:
    metadata:
      labels:
        app.kubernetes.io/service: {{ $service.name }}
        {{- if $service.podLabels }}
          {{- toYaml $service.podLabels | nindent 8 }}
        {{- else }}
          {{- include "common.labels" . | nindent 8 }}
        {{- end }}
      annotations:
      {{- if $service.podAnnotations }}
        {{- toYaml $service.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: "OnFailure"
      terminationGracePeriodSeconds: {{ $service.terminationGracePeriodSeconds | default 30 }}
      {{- if $service.serviceAccountName }}
      serviceAccountName: {{ $service.serviceAccountName }}
      automountServiceAccountToken: {{ $service.automountServiceAccountToken | default true }}
      {{- end }}
      {{- with (or $service.image.pullSecrets .Values.global.image.pullSecrets) }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      initContainers:
        {{- include "wait-for-minio" . | nindent 8 }}
      containers:
        - name: {{ $service.name }}
          image: {{ include "common.image" (list . $service.image) }}
          imagePullPolicy: {{ or $service.image.pullPolicy .Values.global.image.pullPolicy }}
          command: [ "/scripts/create_minio_buckets.sh" ]
          envFrom:
            - secretRef:
                name: {{ $serviceName }}
          {{- with $service.environments }}
          env:
          {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- if $service.resources }}
          resources:
            {{- toYaml $service.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: init-scripts
              mountPath: /scripts
              readOnly: true
          {{- if $service.livenessProbe }}
          livenessProbe:
            {{- toYaml $service.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $service.readinessProbe }}
          readinessProbe:
            {{- toYaml $service.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if $service.startupProbe }}
          startupProbe:
            {{- toYaml $service.startupProbe | nindent 12 }}
          {{- end }}
          {{- if $service.securityContext }}
          securityContext:
            {{- toYaml $service.securityContext | nindent 12 }}
          {{- end }}
          {{- if $service.lifecycle }}
          lifecycle:
            {{- toYaml $service.lifecycle | nindent 12 }}
          {{- end }}
          {{- if $service.stdin }}
          stdin: {{ $service.stdin }}
          {{- end }}
          {{- if $service.tty }}
          tty: {{ $service.tty }}
          {{- end }}
      volumes:
        - name: init-scripts
          configMap:
            name: {{ $serviceName }}
            defaultMode: 0744
      {{- if $service.nodeSelector }}
      nodeSelector:
        {{- toYaml $service.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $service.tolerations }}
      tolerations:
        {{- toYaml $service.tolerations | nindent 8 }}
      {{- end }}
      {{- if $service.affinity }}
      affinity:
        {{- toYaml $service.affinity | nindent 8 }}
      {{- end }}
      {{- if $service.podSecurityContext }}
      securityContext:
        {{- toYaml $service.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if $service.hostname }}
      hostname: {{ $service.hostname }}
      {{- end }}
      {{- if $service.subdomain }}
      subdomain: {{ $service.subdomain }}
      {{- end }}
{{- end }}
