{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.enabled .Values.global.deployment.enabled }}
{{- $registry := (include "registry.external.endpoint" . | trimPrefix "http://" | trimPrefix "https://") }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace (include "common.names.custom" .)).data -}}
{{- $username := include "csghub.registry.username" . -}}
{{- $password := include "csghub.registry.password" . -}}
{{- $htpasswd := htpasswd $username $password -}}
{{- if $secretData }}
{{- $secretUsername := index $secretData "REGISTRY_USERNAME" }}
{{- if $secretUsername }}
{{- $username = $secretUsername | b64dec }}
{{- end }}
{{- $secretPassword := index $secretData "REGISTRY_PASSWORD" }}
{{- if $secretPassword }}
{{- $password = $secretPassword | b64dec }}
{{- end }}
{{- $secretHtpasswd := index $secretData "htpasswd" }}
{{- if $secretHtpasswd }}
{{- $htpasswd = $secretHtpasswd | b64dec }}
{{- end }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    resource.dependencies/statefulsets: |
      {{ include "common.names.custom" . }}
      {{ include "common.names.custom" (list . "builder") }}
type: Opaque
data:
  htpasswd: {{ $htpasswd | b64enc }}
  REGISTRY_USERNAME: {{ $username | b64enc }}
  REGISTRY_PASSWORD: {{ $password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" (list . "registry-docker-config") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $registry $username $password (printf "%s:%s" $username $password | b64enc) | b64enc }}
{{- end }}


