{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.enabled }}
{{- $registry := (include "registry.external.endpoint" . | trimPrefix "http://" | trimPrefix "https://") }}
{{- $secretData := (lookup "v1" "Secret" .Release.Namespace (include "common.names.custom" .)).data -}}
{{- $username := "registry" -}}
{{- $password := randAlphaNum 15 -}}
{{- $htpasswd := htpasswd $username $password -}}
{{- if $secretData }}
{{- $username = index $secretData "REGISTRY_USERNAME" | b64dec -}}
{{- $password = index $secretData "REGISTRY_PASSWORD" | b64dec -}}
{{- $htpasswd = index $secretData "htpasswd" | b64dec -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    resource.dependencies/statefulsets: >
      {{ include "common.names.custom" . }}
      {{ include "common.names.custom" (list . "builder") }}
type: Opaque
data:
  htpasswd: {{ $htpasswd | b64enc }}
  REGISTRY_USERNAME: {{ $username | b64enc }}
  REGISTRY_PASSWORD: {{ $password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" (list . "registry-docker-config") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $registry $username $password (printf "%s:%s" $username $password | b64enc) | b64enc }}
{{- end }}


