{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.global.registry.enabled .Values.global.deploy.enabled }}
{{- $objectStoreConfig := include "chart.objectStoreConfig" (dict "service" .Values "global" .) | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
data:
  REGISTRY_AUTH: "htpasswd"
  REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
  REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"
  REGISTRY_STORAGE: s3
  REGISTRY_STORAGE_REDIRECT_DISABLE: "true"
  REGISTRY_STORAGE_S3_REGIONENDPOINT: {{ $objectStoreConfig.endpoint }}
  {{- if not .Values.global.objectStore.enabled }}
  REGISTRY_STORAGE_S3_ACCESSKEY: {{ $objectStoreConfig.accessKey }}
  REGISTRY_STORAGE_S3_SECRETKEY: {{ $objectStoreConfig.secretKey }}
  {{- end }}
  REGISTRY_STORAGE_S3_REGION: {{ $objectStoreConfig.region }}
  REGISTRY_STORAGE_S3_BUCKET: {{ $objectStoreConfig.bucket }}
  REGISTRY_STORAGE_S3_ENCRYPT: {{ $objectStoreConfig.encrypt | quote }}
  REGISTRY_STORAGE_S3_SECURE: {{ $objectStoreConfig.secure | quote }}
  REGISTRY_STORAGE_S3_FORCEPATHSTYLE: {{ $objectStoreConfig.pathStyle | quote }}
{{- end }}
