{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $registryConfig := include "chart.registryConfig" (dict "service" .Values "global" .) | fromYaml }}
{{- if and .Values.global.registry.enabled .Values.global.deploy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  htpasswd: {{ $registryConfig.htpasswd | b64enc }}
  REGISTRY_USERNAME: {{ $registryConfig.username | b64enc }}
  REGISTRY_PASSWORD: {{ $registryConfig.password | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" (list . "registry-docker-config") }}
  {{- $registrySecretNamespace := .Values.global.deploy.imageBuilder.namespace }}
  {{- if eq .Values.global.deploy.mergingNamespace "Multi" }}
  {{- $registrySecretNamespace = .Values.global.deploy.namespace }}
  {{- else if eq .Values.global.deploy.mergingNamespace "Single" }}
  {{- $registrySecretNamespace = .Release.Namespace }}
  {{- end }}
  namespace: {{ $registrySecretNamespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $registryConfig.repository $registryConfig.username $registryConfig.password (printf "%s:%s" $registryConfig.username $registryConfig.password | b64enc) | b64enc }}


