{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.global.registry.enabled }}
{{- $registryConfig := include "chart.registryConfig" (dict "service" .Values "global" .) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  htpasswd: {{ $registryConfig.htpasswd | b64enc }}
  REGISTRY_USERNAME: {{ $registryConfig.username | b64enc }}
  REGISTRY_PASSWORD: {{ $registryConfig.password | b64enc }}
{{- end }}