{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "ingress-nginx-custom-errors"
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "custom-error-pages") | nindent 4 }}
data:
{{- $currentScope := . }}
{{- range $path, $_ := .Files.Glob "html/*.html" }}
{{- with $currentScope }}
{{- base $path | nindent 2 }}: |
{{- .Files.Get $path | nindent 4 }}
{{- end }}
{{- end }}
