{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if and .Values.global.redis.enabled (not .Values.chartContext.isBuiltIn) .Values.redis.requirePass }}
{{- $redisConfig := include "csghub.redis.config" (dict "service" .Values "global" .) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" (list . "redis") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  REDIS_PASSWD: {{ $redisConfig.password | b64enc }}
{{- end }}
