{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if and .Values.global.redis.enabled (not .Values.chartContext.isBuiltIn) }}
{{- $redisConfig := include "csghub.redis.config" (dict "service" .Values "global" .) | fromYaml }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "redis") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ $redisConfig.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
{{- end }}
