{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.global.autoConfigure }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.custom" (list . "auto-configure") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "auto-configure") | nindent 4 }}
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 10
  activeDeadlineSeconds: 600
  template:
    metadata:
      name: {{ include "common.names.custom" (list . "auto-configure") }}
      labels: {{ include "common.labels" (dict "context" . "service" "auto-configure") | nindent 8 }}
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: "runner-admin"
      automountServiceAccountToken: true
      {{- end }}
      restartPolicy: OnFailure
      {{- with (or .Values.image.pullSecrets .Values.global.image.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: resource-verify
          image: {{ or .Values.image.registry .Values.global.image.registry "docker.io" }}/opencsghq/omnibus-csghub:toolbox-1.2.6
          imagePullPolicy: {{ or .Values.image.pullPolicy .Values.global.image.pullPolicy }}
          command: [ "/opt/csghub/bin/kyml", "-file", "/yamls", "-create" ]
          volumeMounts:
            - name: argo
              mountPath: /yamls/argo
            - name: knative
              mountPath: /yamls/knative
            - name: lws
              mountPath: /yamls/lws
      volumes:
        - name: argo
          configMap:
            name: {{ include "common.names.custom" (list . "runner-argo") }}
        - name: knative
          configMap:
            name: {{ include "common.names.custom" (list . "runner-knative") }}
        - name: lws
          configMap:
            name: {{ include "common.names.custom" (list . "runner-lws") }}
{{- end }}
