{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $registrySecretName := (include "common.names.custom" (list . "registry")) -}}
{{- $registrySecret := (lookup "v1" "Secret" .Release.Namespace $registrySecretName) -}}
{{- $registryConfig := include "chart.registryConfig" (dict "service" .Values "global" .) | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" (list . "docker-credential") }}
  namespace: {{ include "namespace.spaces" . }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/dockerconfigjson
data:
  {{- with .Values.registry }}
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $registryConfig.registry $registryConfig.username $registryConfig.password (printf "%s:%s" $registryConfig.username $registryConfig.password | b64enc) | b64enc }}
  {{- end }}