{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.global.deployment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    resource.dependencies/deployments: |
      {{ include "common.names.custom" (list . "runner") }}
    resource.dependencies/statefulsets: |
      {{ include "common.names.custom" . }}
data:
  SPACE_DATA_PATH: "/opt/data"
  # Redis
  REDIS_ENDPOINT: {{ include "csghub.redis.endpoint" . }}
  REDIS_HOST: {{ include "csghub.redis.host" . }}
  REDIS_PORT: {{ include "csghub.redis.port" . | quote }}
  {{- if .Values.global.redis.external }}
  REDIS_PASSWD: {{ include "csghub.redis.password" . }}
  {{- end }}
  # Registry
  REGISTRY_ADDRESS: {{ include "csghub.registry.repository" . }}
  REGISTRY_NAMESPACE: {{ include "csghub.registry.namespace" . }}
  {{- if .Values.global.registry.external }}
  REGISTRY_USERNAME: {{ include "csghub.registry.username" . }}
  REGISTRY_PASSWORD: {{ include "csghub.registry.password" . }}
  {{- end }}
---
{{- if and .Values.global.registry.external .Values.global.registry.insecure }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" (list . "builder-docker-daemon") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
data:
  daemon.json: |
    {
      "insecure-registries": [
        "{{ or (include "csghub.registry.repository" .) .Values.registry.repository }}"
      ]
    }
{{- else if not .Values.global.registry.external }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" (list . "builder-docker-daemon") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
data:
  daemon.json: |
    {
      "insecure-registries": [
        "{{ include "registry.external.endpoint" . | trimPrefix  "http://" | trimPrefix  "https://" }}"
      ]
    }
{{- end }}
{{- end }}
