{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "service" "dataflow" "global" .) | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- $pgConfig := include "common.postgresql.config" (dict "service" $service "global" .) | fromYaml }}
{{- $redisConfig := include "common.redis.config" (dict "service" $service "global" .) | fromYaml }}
{{- $mongoConfig := include "common.mongo.config" (dict "service" $service "global" .) | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
data:
  ## Dataflow configuration
  {{- if $service.chartContext.isBuiltIn }}
  CSGHUB_ENDPOINT: {{ include "common.endpoint.csghub" . | quote }}
  {{- else }}
  CSGHUB_ENDPOINT: {{ .Values.externalUrl | quote }}
  {{- end }}
  DATA_DIR: "/data/dataflow"
  MAX_WORKERS: "99"
  RAY_ADDRESS: "auto"
  RAY_ENABLE: "False"
  RAY_LOG_DIR: "/home/output"
  API_SERVER: "0.0.0.0"
  API_PORT: "8000"
  ENABLE_OPENTELEMETRY: "False"
  DATABASE_HOSTNAME: {{ $pgConfig.host | quote }}
  DATABASE_PORT: {{ $pgConfig.port | quote }}
  DATABASE_DB: {{ $pgConfig.database | quote }}
  DATABASE_USERNAME: {{ $pgConfig.user | quote }}
  DATABASE_PASSWORD: {{ $pgConfig.password | quote }}
  STUDIO_JUMP_URL: {{ include "common.endpoint.labelstudio" . | quote }}
  REDIS_HOST_URL: {{ printf "redis://%s:%v" $redisConfig.host $redisConfig.port | quote }}
  MONG_HOST_URL: {{ printf "mongodb://%s:%s@%s:%v" $mongoConfig.user $mongoConfig.password $mongoConfig.host $mongoConfig.port | quote }}
