{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $pgConfig := include "csghub.postgresql.config" (dict "service" .Values.dataflow "global" .) | fromYaml }}
{{- $redisConfig := include "csghub.redis.config" (dict "service" .Values.dataflow "global" .) | fromYaml }}
{{- $mongoConfig := include "csghub.mongo.config" (dict "service" .Values.dataflow "global" .) | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" (list . "dataflow") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "dataflow") | nindent 4 }}
data:
{{- if .Values.chartContext.isBuiltIn }}
  CSG_HUB_ENDPOINT: {{ include "csghub.internal.endpoint" . | quote }}
{{- else }}
  CSG_HUB_ENDPOINT: {{ .Values.externalUrl | quote }}
{{- end }}
  DATA_DIR: "/data/dataflow"
  MAX_WORKERS: "99"
  RAY_ADDRESS: "auto"
  RAY_ENABLE: "False"
  RAY_LOG_DIR: "/home/output"
  API_SERVER: "0.0.0.0"
  API_PORT: "8000"
  ENABLE_OPENTELEMETRY: "False"
  DATABASE_HOSTNAME: {{ $pgConfig.host | quote }}
  DATABASE_PORT: {{ $pgConfig.port | quote }}
  DATABASE_DB: {{ $pgConfig.database | quote }}
  DATABASE_USERNAME: {{ $pgConfig.user | quote }}
  DATABASE_PASSWORD: {{ $pgConfig.password | quote }}
  {{- $labelStudioHost := include "common.names.custom" (list . "label-studio") }}
  {{- $labelStudioPort := include "csghub.svc.port" "label-studio" }}
  STUDIO_JUMP_URL: {{ printf "http://%s:%s" $labelStudioHost $labelStudioPort | quote }}
  {{- $redisHost := $redisConfig.host }}
  {{- $redisPort := $redisConfig.port }}
  REDIS_HOST_URL: {{ printf "redis://%s:%s" $redisHost $redisPort | quote }}
  {{- $mongoHost := $mongoConfig.host }}
  {{- $mongoPort := $mongoConfig.port }}
  {{- $mongoUser := $mongoConfig.user }}
  {{- $mongoPass := $mongoConfig.password }}
  MONG_HOST_URL: {{ printf "mongodb://%s:%s@%s:%s" $mongoUser $mongoPass $mongoHost $mongoPort | quote }}
