{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $redisConfig := include "csghub.redis.config" (dict "service" .Values.dataflow "global" .) | fromYaml }}
{{- $mongoConfig := include "csghub.mongo.config" (dict "service" .Values.dataflow "global" .) | fromYaml }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.custom" (list . "dataflow") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
    {{- with .Values.dataflow.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "common.labels.selector" . | nindent 6 }}
  serviceName: {{ include "common.names.custom" (list . "dataflow") }}
  replicas: 1
  minReadySeconds: 30
  template:
    metadata:
      annotations:
      {{- with .Values.dataflow.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- include "common.labels" . | nindent 8 }}
    spec:
      {{- with (or .Values.dataflow.image.pullSecrets .Values.image.pullSecrets .Values.global.image.pullSecrets) }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      {{- with .Values.dataflow.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: wait-for-postgresql
          image: {{ include "image.fixed.prefix" (list . "opencsghq/psql:latest") }}
          imagePullPolicy: {{ or .Values.dataflow.image.pullPolicy .Values.image.pullPolicy .Values.global.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              until psql {{ include "csghub.postgresql.dsn" (dict "service" .Values.dataflow "global" .) | quote }} -c 'SELECT 1';
              do
                echo 'Wait for PostgreSQL to be ready';
                sleep 2;
              done;
        - name: wait-for-redis
          image: {{ include "image.generic.prefix" (list . .Values.redis.image) }}
          imagePullPolicy: {{ or .Values.dataflow.image.pullPolicy .Values.image.pullPolicy .Values.global.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              until redis-cli -u "$REDIS_HOST_URL" ping;
              do
                echo 'Wait for Redis to be ready';
                sleep 2;
              done;
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" (list . "dataflow") }}
        - name: wait-for-mongo
          image: {{ include "image.generic.prefix" (list . .Values.mongo.image) }}
          imagePullPolicy: {{ or .Values.dataflow.image.pullPolicy .Values.image.pullPolicy .Values.global.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              until mongosh "$MONG_HOST_URL"/admin --eval "db.adminCommand('ping')" | grep "ok.*1";
              do
                echo 'Wait for Mongo to be ready';
                sleep 2;
              done;
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" (list . "dataflow") }}
      containers:
        - name: dataflow
          image: {{ include "image.generic.prefix" (list . .Values.dataflow.image) }}
          imagePullPolicy: {{ or .Values.dataflow.image.pullPolicy .Values.image.pullPolicy .Values.global.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              uvicorn data_server.main:app --host 0.0.0.0 --port 8000
          ports:
            - containerPort: 8000
              name: dataflow
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" (list . "dataflow") }}
          {{- with .Values.dataflow.environments }}
          env:
          {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          resources:
            {{- .Values.dataflow.resources | toYaml | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            {{- .Values.dataflow.podSecurityContext | toYaml | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data/dataflow
      {{- with .Values.dataflow.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataflow.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataflow.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        namespace: {{ .Release.Namespace }}
        labels:
          {{- include "common.labels" . | nindent 10 }}
        annotations:
          helm.sh/resource-policy: keep
          {{- with .Values.dataflow.annotations }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      spec:
        accessModes: {{ or .Values.dataflow.persistence.accessMode .Values.global.persistence.accessMode }}
        {{- if (or .Values.dataflow.persistence.storageClass .Values.global.persistence.storageClass) }}
        storageClassName: {{ or .Values.dataflow.persistence.storageClass .Values.global.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ or .Values.dataflow.persistence.size .Values.global.persistence.size }}
