apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  namespace: workflows
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor
  namespace: workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor
  namespace: workflows
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
subjects:
  - kind: ServiceAccount
    name: executor
    namespace: workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  namespace: workflows-quota
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor
  namespace: workflows-quota
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor
  namespace: workflows-quota
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
subjects:
  - kind: ServiceAccount
    name: executor
    namespace: workflows-quota
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-image-factory-secret-access
  namespace: image-factory
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-image-factory-secret-access
  namespace: image-factory
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-image-factory-secret-access
subjects:
  - kind: ServiceAccount
    name: argo
    namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  namespace: image-factory
rules:
  # Pod 相关权限
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - pods/exec
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
  # Argo Workflows 相关权限
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtaskresults
      - workflowtemplates
      - cronworkflows
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # 服务和配置相关权限
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: executor
  namespace: image-factory
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor
  namespace: image-factory
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
subjects:
  - kind: ServiceAccount
    name: executor
    namespace: image-factory
---
