{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if not .Values.global.redis.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    resource.dependencies/deployments: |
      {{ include "common.names.custom" (list . "mirror") }}
      {{ include "common.names.custom" (list . "proxy") }}
      {{ include "common.names.custom" (list . "server") }}
      {{ include "common.names.custom" (list . "dataviewer") }}
    resource.dependencies/statefulsets: |
      {{ include "common.names.custom" . }}
      {{ include "common.names.custom" (list . "builder") }}
type: Opaque
data:
  {{- $password := include "csghub.redis.password" . | b64enc }}
  {{- $secretData := (lookup "v1" "Secret" .Release.Namespace (include "common.names.custom" .)).data }}
  {{- if $secretData }}
  {{- $secretPass := index $secretData "REDIS_PASSWD" }}
  {{- if $secretPass }}
  {{- $password = $secretPass }}
  {{- end }}
  {{- end }}
  REDIS_PASSWD: {{ $password | quote }}
{{- end }}