{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- $service := include "common.service" (dict "ctx" . "service" "gitlabShell") | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . "ssh-keys") }}
{{- $legacyServiceName := include "common.names.custom" (list . $service.name) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $serviceName }}
{{- if not $existingSecret }}
{{- $existingSecret = lookup "v1" "Secret" .Release.Namespace $legacyServiceName }}
{{- end }}
{{- $existingData := ($existingSecret.data) | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  ssh_host_rsa_key: {{ dig "ssh_host_rsa_key" (genPrivateKey "rsa" | b64enc) $existingData | quote }}
  ssh_host_ecdsa_key: {{ dig "ssh_host_ecdsa_key" (genPrivateKey "ecdsa" | b64enc) $existingData | quote }}
  ssh_host_ed25519_key: {{ dig "ssh_host_ed25519_key" (genPrivateKey "ed25519" | b64enc) $existingData | quote }}
