{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.enabled .Values.global.deployment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    resource.dependencies/deployments: >
      {{ include "common.names.custom" . }}
      {{ include "common.names.custom" (list . "proxy") }}
data:
  corefile: |
    .:53 {
        {{- range .Values.global.deployment.knative.serving.services }}
        forward {{ printf "%s.%s." $.Values.global.deployment.namespace .host }} /etc/resolv.conf
        {{- end  }}
        forward . {{ include "system.coredns.ip" . }}
        log
        errors
        cache 30
        reload
        loadbalance
    }
    {{- range .Values.global.deployment.knative.serving.services }}
    {{ .host }}:53 {
        file /var/opt/coredns/{{ .host }}
        log
        errors
    }
    {{- end }}
  {{- range .Values.global.deployment.knative.serving.services }}
  {{ .host }}: |
    {{- $domain := (printf "%s.%s." $.Values.global.deployment.namespace .host) }}
    $ORIGIN {{ $domain }}
    @ 3600 IN SOA ns1.{{ $domain }} admin.{{ $domain }} (
        2022042401 ; Serial
        3600       ; Refresh
        1800       ; Retry
        604800     ; Expire
        86400      ; Minimum TTL
    )
    *   3600 IN A
  {{- end }}
{{- end }}