{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "proxy") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "proxy") | nindent 4 }}
spec:
  type: {{ .Values.csghub.proxy.service.type }}
  clusterIP: {{ include "proxy.nginx.ip" . }}
  ports:
    - port: {{ .Values.csghub.proxy.service.port }}
      targetPort: 8083
      protocol: TCP
      name: proxy
    - port: 80
      targetPort: 80
      protocol: TCP
      name: proxy-nginx
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "proxy") | nindent 4 }}