{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if and .Values.global.postgresql.enabled (not .Values.dataflow.chartContext.isBuiltIn) }}
{{- $service := include "common.service" (dict "service" "postgresql" "global" .) | fromYaml }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
data:
  runtime.conf: |
    include_if_exists = '/var/lib/postgresql/data/postgresql.conf'
    {{- range $key, $value := $service.parameters -}}
      {{- if and $key $value }}
    {{ printf "%s = %s" $key ($value | toString | squote ) }}
      {{- end }}
    {{- end }}
{{- end }}
