{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if and .Values.global.postgresql.enabled (not .Values.chartContext.isBuiltIn) }}
{{- $pgConfig := include "csghub.postgresql.config" (dict "service" .Values "global" .) | fromYaml }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "postgresql") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ $pgConfig.port }}
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
{{- end }}
