{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.gitaly (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ $conf.service.port }}
      targetPort: 8000
      protocol: TCP
      name: dataflow
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
{{- end }}