{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" (list . "accounting")}}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "accounting") | nindent 4 }}
  annotations:
    resource.dependencies/deployments: |
      {{ include "common.names.custom" (list . "accounting") }}
data:
  OPENCSG_ACCOUNTING_SERVER_PORT: {{ include "csghub.svc.port" "accounting" | quote }}
  OPENCSG_ACCOUNTING_FEE_EVENT_SUBJECT: "accounting.fee.>"
  OPENCSG_ACCOUNTING_NOTIFY_NOBALANCE_SUBJECT: "accounting.notify.nobalance"
  OPENCSG_ACCOUNTING_MSG_FETCH_TIMEOUTINSEC: "5"
  OPENCSG_ACCOUNTING_CHARGING_ENABLE: "true"
