{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $objectStoreConfig := include "chart.objectStoreConfig" (dict "service" .Values.csghub.server "global" .) | fromYaml }}
{{- $redisConfig := include "csghub.redis.config" (dict "service" .Values.csghub.server "global" .) | fromYaml }}
{{- $pgConfig := include "csghub.postgresql.config" (dict "service" .Values.csghub.server "global" .) | fromYaml }}
{{- $gitConfig := include "csghub.gitaly.config" (dict "service" .Values.csghub.server "global" .) | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" (list . "server") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "server") | nindent 4 }}
data:
  GIN_MODE: release
  STARHUB_SERVER_SAAS: "false"
  STARHUB_SERVER_MIRRORSERVER_ENABLE: "false"
  STARHUB_SERVER_MIRRORSERVER_HOST: ""
  {{- $token := include "server.hub.api.token" . }}
  {{- $tokenConfigMap := include "common.names.custom" (list . "server") -}}
  {{- $tokenConfigMapData := (lookup "v1" "ConfigMap" .Release.Namespace $tokenConfigMap).data }}
  {{- if $tokenConfigMapData }}
  {{- $tokenFromConfigMap := index $tokenConfigMapData "STARHUB_SERVER_API_TOKEN" }}
  {{- if eq (len $tokenFromConfigMap) 128 }}
  {{- $token = $tokenFromConfigMap }}
  {{- end }}
  {{- end }}
  STARHUB_SERVER_API_TOKEN: {{ $token | quote }}
  STARHUB_SERVER_MIRROR_REMOTE: "false"
  STARHUB_SERVER_MODEL_DOWNLOAD_ENDPOINT: {{ include "csghub.external.endpoint" . | quote }}
  STARHUB_JWT_SIGNING_KEY: "e2kk6awudc3620ed9a"

  # Multiple-Sync Enabled
  STARHUB_SERVER_MULTI_SYNC_ENABLED: "true"
  # Multiple-Sync fetch timeout
  STARHUB_SERVER_GIT_OPERATION_TIMEOUT: "120"

  # Redis Connection Info
  STARHUB_SERVER_REDIS_ENDPOINT: {{ printf "%s:%v" $redisConfig.host $redisConfig.port | quote }}
  {{- if not .Values.global.redis.enabled }}
  STARHUB_SERVER_REDIS_PASSWORD: {{ $redisConfig.password | quote }}
  {{- end }}

  # PostgreSQL Connection Info
  STARHUB_DATABASE_HOST: {{ $pgConfig.host }}
  STARHUB_DATABASE_PORT: {{ $pgConfig.port | quote }}
  STARHUB_DATABASE_USERNAME: {{ $pgConfig.user }}
  STARHUB_DATABASE_PASSWORD: {{ $pgConfig.password }}
  STARHUB_DATABASE_NAME: {{ $pgConfig.database }}
  STARHUB_DATABASE_TIMEZONE: {{ $pgConfig.timezone }}
  STARHUB_DATABASE_DSN: {{ include "csghub.postgresql.url" (dict "service" .Values.csghub.server "global" .) | quote }}

  # Object Storage Connection Info
  STARHUB_SERVER_S3_ENDPOINT: {{ include "minio.external.endpoint" . | trimPrefix "http://" | trimPrefix  "https://" | quote }}
  {{- if not .Values.global.objectStore.enabled }}
  STARHUB_SERVER_S3_ACCESS_KEY_ID: {{ $objectStoreConfig.accessKey }}
  STARHUB_SERVER_S3_ACCESS_KEY_SECRET: {{ $objectStoreConfig.secretKey }}
  {{- end }}
  STARHUB_SERVER_S3_BUCKET: {{ $objectStoreConfig.bucket }}
  STARHUB_SERVER_S3_REGION: {{ $objectStoreConfig.region }}
  STARHUB_SERVER_S3_ENABLE_SSL: {{ $objectStoreConfig.secure | quote }}
  {{- if eq $objectStoreConfig.pathStyle "true" }}
  STARHUB_SERVER_S3_BUCKET_LOOKUP: "path"
  {{- else }}
  STARHUB_SERVER_S3_BUCKET_LOOKUP: "auto"
  {{- end }}
  STARHUB_SERVER_SKIP_LFS_FILE_VALIDATION: {{ .Values.csghub.server.objectStore.directUpload | quote }}

  # Gitaly Connection Info
  STARHUB_SERVER_GITSERVER_TYPE: "gitaly"
  STARHUB_SERVER_GITALY_SERVER_SOCKET: {{ include "csghub.gitaly.grpcEndpoint" (dict "service" .Values.csghub.server "global" .) }}
  STARHUB_SERVER_GITALY_TOKEN: {{ $gitConfig.token }}
  STARHUB_SERVER_GITALY_STORAGE: {{ $gitConfig.storage }}
  STARHUB_SERVER_CHECK_FILE_SIZE_ENABLED: {{ not $gitConfig.isCluster | quote }}
  {{- if eq (include "gitlab-shell.external.port" .) "22" }}
  STARHUB_SERVER_SSH_DOMAIN: {{ printf "ssh://git@%s" (include "csghub.external.domain" .)}}
  {{- else }}
  STARHUB_SERVER_SSH_DOMAIN: {{ printf "ssh://git@%s:%s" (include "csghub.external.domain" .) (include "gitlab-shell.external.port" .) }}
  {{- end }}

  # Accounting
  OPENCSG_ACCOUNTING_SERVER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "accounting")) | quote }}
  OPENCSG_ACCOUNTING_SERVER_PORT: {{ include "csghub.svc.port" "accounting" | quote }}

  # User
  OPENCSG_USER_SERVER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "user")) | quote }}
  OPENCSG_USER_SERVER_PORT: {{ include "csghub.svc.port" "user" | quote }}

  # Space Application
  STARHUB_SERVER_SPACE_BUILDER_ENDPOINT: {{ printf "http://%s:%s" (include "common.names.custom" (list . "runner")) (include "csghub.svc.port" "runner") | quote }}
  STARHUB_SERVER_SPACE_RUNNER_ENDPOINT: {{ printf "http://%s:%s" (include "common.names.custom" (list . "runner")) (include "csghub.svc.port" "runner") | quote }}
  STARHUB_SERVER_PUBLIC_DOMAIN: {{ include "csghub.external.endpoint" . }}
  STARHUB_SERVER_MODEL_DOCKER_REG_BASE: "opencsg-registry.cn-beijing.cr.aliyuncs.com/public"

  # Deprecated ==> re-enabled
  {{- if .Values.global.deploy.usePublicDomain }}
  STARHUB_SERVER_PUBLIC_ROOT_DOMAIN: {{ include "csghub.external.public.endpoint" . | trimPrefix "http://" | trimPrefix "https://" | quote }}
  {{- else }}
  STARHUB_SERVER_PUBLIC_ROOT_DOMAIN: ""
  {{- end }}

  # Deprecated
  STARHUB_SERVER_INTERNAL_ROOT_DOMAIN: {{ printf "%s.app.internal:%s" .Values.global.deploy.namespace (include "csghub.svc.port" "rproxy") | quote }}

  # Casdoor
  STARHUB_SERVER_CASDOOR_CERTIFICATE: "/starhub-bin/casdoor/tls.crt"

  # Workflow
  OPENCSG_WORKFLOW_SERVER_ENDPOINT: {{ include "temporal.internal.endpoint" . }}

  # Dataflow
  {{- if .Values.global.dataflow.enabled }}
  OPENCSG_DATAFLOW_SERVER_HOST: {{ printf "http://%s" (include "dataflow.internal.domain" .) }}
  OPENCSG_DATAFLOW_SERVER_PORT: {{ include "dataflow.internal.port" . | quote }}
  {{- end }}

  # Dataviewer
  OPENCSG_DATAVIEWER_SERVER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "dataviewer")) | quote }}
  OPENCSG_DATAVIEWER_SERVER_PORT: {{ include "csghub.svc.port" "dataviewer" | quote }}

  # Moderation
  {{- if .Values.global.moderation.enabled }}
  STARHUB_SERVER_SENSITIVE_CHECK_ENABLE: "true"
  OPENCSG_MODERATION_SERVER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "gateway")) | quote }}
  OPENCSG_MODERATION_SERVER_PORT: {{ include "csghub.svc.port" "moderation" | quote }}
  {{- else }}
  STARHUB_SERVER_SENSITIVE_CHECK_ENABLE: "false"
  {{- end }}

  STARHUB_SERVER_CRON_JOB_SYNC_AS_CLIENT_CRON_EXPRESSION: '*/5 * * * *'

  OPENCSG_TRACING_OTLP_LOGGING: "false"

  STARHUB_SERVER_SPACE_PYPI_INDEX_URL: {{ .Values.global.deploy.pipIndexUrl | quote}}

  # Notification
  STARHUB_SERVER_NOTIFIER_HOST: {{ printf "http://%s" (include "common.names.custom" (list . "notification")) | quote }}
  STARHUB_SERVER_NOTIFIER_PORT: {{ include "csghub.svc.port" "notification" | quote }}
