{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
{{- $RedisConfig := include "csghub.redis.config" (dict "service" .Values.csghub.mirror "global" .) | fromYaml }}
kind: Deployment
metadata:
  name: {{ include "common.names.custom" (list . "mirror") }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" (dict "context" . "service" "mirror") | nindent 4 }}
  annotations: {{ .Values.csghub.mirror.annotations | toYaml | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "mirror") | nindent 6 }}
  replicas: {{ .Values.csghub.mirror.replicas }}
  revisionHistoryLimit: 1
  minReadySeconds: 30
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-server.yaml") . | sha256sum }}
        {{- with .Values.csghub.mirror.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "common.labels" (dict "context" . "service" "mirror") | nindent 8 }}
    spec:
      {{- with (or .Values.global.image.pullSecrets .Values.csghub.mirror.image.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      {{- with .Values.csghub.mirror.securityContext }}
      securityContext:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      {{- if .Values.csghub.mirror.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.custom" (list . "mirror") }}
      automountServiceAccountToken: {{ .Values.csghub.mirror.serviceAccount.automount }}
      {{- end }}
      initContainers:
        - name: wait-for-redis
          image: {{ or .Values.global.image.registry .Values.csghub.mirror.image.registry }}/redis:7.2.5
          imagePullPolicy: {{ .Values.csghub.mirror.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until redis-cli -h {{ $RedisConfig.host }} -p {{ $RedisConfig.port }} ping; do echo 'Wait for Redis to be ready'; sleep 2; done" ]
          envFrom:
            {{- if .Values.global.redis.enabled }}
            - configMapRef:
                name: {{ include "common.names.custom" (list . "server") }}
            {{- else }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "redis") }}
            {{- end }}
          env:
            - name: REDISCLI_AUTH
              {{- if .Values.global.redis.enabled }}
              value: "$(STARHUB_SERVER_REDIS_PASSWORD)"
              {{- else }}
              value: "$(REDIS_PASSWD)"
              {{- end }}
        - name: wait-for-postgresql
          image:  {{ or .Values.global.image.registry .Values.csghub.mirror.image.registry }}/opencsg/psql:latest
          imagePullPolicy: {{ .Values.csghub.mirror.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until pg_isready -d \"{{ include "csghub.postgresql.dsn" (dict "service" .Values.csghub.mirror "global" .) }}\"; do echo 'Wait for PostgreSQL to be ready'; sleep 2; done" ]
        - name: wait-for-server
          image: {{ or .Values.global.image.registry .Values.csghub.mirror.image.registry }}/busybox:latest
          imagePullPolicy: {{ .Values.csghub.mirror.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until nc -z {{ include "common.names.custom" (list . "server") }} {{ include "csghub.svc.port" "server" }}; do echo 'Wait for csghub-server to be ready'; sleep 2; done" ]
      containers:
        - name: mirror-repo
          image: {{ or .Values.global.image.registry .Values.csghub.mirror.image.registry }}/{{ or .Values.global.image.name .Values.csghub.mirror.image.repository }}:{{ include "csghub.image.tag" (dict "tag" (or .Values.global.image.tag .Values.csghub.mirror.image.tag) "context" .) }}
          imagePullPolicy: {{ or .Values.global.image.pullPolicy .Values.csghub.mirror.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "update-ca-certificates && /starhub-bin/starhub mirror repo-sync" ]
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" (list . "server") }}
            {{- if not .Values.global.redis.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "redis") }}
            {{- end }}
            {{- if .Values.global.objectStore.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "minio") }}
            {{- end }}
          env:
            {{- if not .Values.global.redis.enabled }}
            - name: STARHUB_SERVER_REDIS_PASSWORD
              value: "$(REDIS_PASSWD)"
            {{- end }}
            {{- if .Values.global.objectStore.enabled }}
            - name: STARHUB_SERVER_S3_ACCESS_KEY_ID
              value: "$(MINIO_ROOT_USER)"
            - name: STARHUB_SERVER_S3_ACCESS_KEY_SECRET
              value: "$(MINIO_ROOT_PASSWORD)"
            {{- end }}
            {{- with .Values.csghub.mirror.environments }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- .Values.csghub.mirror.resources | toYaml | nindent 12 }}
          securityContext:
            {{- .Values.csghub.mirror.podSecurityContext | toYaml | nindent 12 }}
        - name: mirror-lfs
          image: {{ or .Values.global.image.registry .Values.csghub.mirror.image.registry }}/{{ or .Values.global.image.name .Values.csghub.mirror.image.repository }}:{{ include "csghub.image.tag" (dict "tag" (or .Values.global.image.tag .Values.csghub.mirror.image.tag) "context" .) }}
          imagePullPolicy: {{ or .Values.global.image.pullPolicy .Values.csghub.mirror.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "update-ca-certificates && /starhub-bin/starhub mirror lfs-sync" ]
          envFrom:
            - configMapRef:
                name: {{ include "common.names.custom" (list . "server") }}
            {{- if not .Values.global.redis.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "redis") }}
            {{- end }}
            {{- if .Values.global.objectStore.enabled }}
            - secretRef:
                name: {{ include "common.names.custom" (list . "minio") }}
            {{- end }}
          env:
            {{- if not .Values.global.redis.enabled }}
            - name: STARHUB_SERVER_REDIS_PASSWORD
              value: "$(REDIS_PASSWD)"
            {{- end }}
            {{- if .Values.global.objectStore.enabled }}
            - name: STARHUB_SERVER_S3_ACCESS_KEY_ID
              value: "$(MINIO_ROOT_USER)"
            - name: STARHUB_SERVER_S3_ACCESS_KEY_SECRET
              value: "$(MINIO_ROOT_PASSWORD)"
            {{- end }}
            {{- with .Values.csghub.mirror.environments }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- .Values.csghub.mirror.resources | toYaml | nindent 12 }}
          securityContext:
            {{- .Values.csghub.mirror.podSecurityContext | toYaml | nindent 12 }}
      {{- with .Values.csghub.mirror.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.csghub.mirror.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.csghub.mirror.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}