{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "server") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "server") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "server" }}
      targetPort: 8080
      protocol: TCP
      name: server
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "server") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "user") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "user") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "user" }}
      targetPort: 8080
      protocol: TCP
      name: user
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "user") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "accounting") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "accounting") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "accounting" }}
      targetPort: 8086
      protocol: TCP
      name: accounting
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "accounting") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "aigateway") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "aigateway") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "aigateway" }}
      targetPort: 8084
      protocol: TCP
      name: aigateway
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "aigateway") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "dataviewer") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "dataviewer") | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ include "csghub.svc.port" "dataviewer" }}
      targetPort: 8093
      protocol: TCP
      name: dataviewer
  selector:
    {{- include "common.labels" (dict "context" . "service" "dataviewer") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "notification") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "notification") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "notification" }}
      targetPort: 8095
      protocol: TCP
      name: notification
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "notification") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "proxy") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "proxy") | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: {{ include "proxy.nginx.ip" . }}
  ports:
    - port: {{ include "csghub.svc.port" "proxy" }}
      targetPort: 8083
      protocol: TCP
      name: proxy
    - port: 80
      targetPort: 80
      protocol: TCP
      name: proxy-nginx
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "proxy") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "portal") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "portal") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "portal" }}
      targetPort: 8090
      protocol: TCP
      name: portal
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "portal") | nindent 4 }}
---
{{- if .Values.global.moderation.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "moderation") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "moderation") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "moderation" }}
      targetPort: 8089
      protocol: TCP
      name: moderation
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "moderation") | nindent 4 }}
{{- end }}
---
{{- if .Values.global.deploy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.custom" (list . "runner") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" (dict "context" . "service" "runner") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "csghub.svc.port" "runner" }}
      targetPort: 8082
      protocol: TCP
      name: runner
  selector:
    {{- include "common.serviceSelectorLabels" (dict "selector" true "context" . "service" "runner") | nindent 4 }}
{{- end }}
---
