{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- $conf := merge .Values.global.moderation (omit .Values "global" "exports") }}
{{- if $conf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ $conf.annotations | toYaml | nindent 4 }}
data:
  STARHUB_SERVER_SENSITIVE_CHECK_ENABLE: "true"
  STARHUB_SERVER_SENSITIVE_CHECK_ACCESS_KEY_ID: {{ $conf.contentCheck.accessKeyId | quote }}
  STARHUB_SERVER_SENSITIVE_CHECK_ACCESS_KEY_SECRET: {{ $conf.contentCheck.accessKeySecret | quote }}
  STARHUB_SERVER_SENSITIVE_CHECK_REGION: {{ $conf.contentCheck.region | quote }}
{{- end }}
