{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.enabled .Values.serviceAccount.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.custom" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  ttlSecondsAfterFinished: 1200
  backoffLimit: 4
  activeDeadlineSeconds: 1200
  template:
    metadata:
      name: {{ include "common.names.custom" . }}
      labels: {{ include "common.labels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "common.names.custom" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- end }}
      restartPolicy: OnFailure
      {{- with (or .Values.global.images.pullSecrets .Values.images.pullSecrets) }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      initContainers:
        - name: wait-for-minio
          image: {{ or .Values.global.images.prefix .Values.images.prefix }}/busybox:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "until wget --spider {{ include "minio.internal.endpoint" . }}/minio/health/live; do echo 'Wait for minio to be ready'; sleep 2; done" ]
      containers:
        - name: kubectl
          image: {{ or .Values.global.images.prefix .Values.images.prefix }}/bitnami/kubectl:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              kubectl patch configmap {{ printf "%s-ingress-nginx-tcp" .Release.Name }} \
                --namespace {{ .Release.Namespace }} \
                --type merge \
                --patch '{"data":{"22":"{{ printf "%s/%s:22" .Release.Namespace (include "gitlab-shell.internal.domain" .) }}"}}'
{{- end }}
