{{- /*
Copyright OpenCSG, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/ -}}

{{- if .Values.global.registry.enabled }}
{{- $service := .Values.registry }}
{{- $serviceName := include "common.names.custom" (list . $service.name) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $serviceName }}

{{- $defaultUser := "registry" }}
{{- $defaultPass := include "common.randomPassword" $service.name }}
{{- $defaultHtpasswd := htpasswd $defaultUser $defaultPass }}

{{- $username := $defaultUser | b64enc }}
{{- $password := $defaultPass | b64enc }}
{{- $htpasswd := $defaultHtpasswd | b64enc }}

{{- if and $existingSecret $existingSecret.data }}
{{- $username = index $existingSecret.data "REGISTRY_USERNAME" | default $username }}
{{- $password = index $existingSecret.data "REGISTRY_PASSWORD" | default $password }}
{{- $htpasswd = index $existingSecret.data "htpasswd" | default $htpasswd }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service: {{ $service.name }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  REGISTRY_USERNAME: {{ $username | quote }}
  REGISTRY_PASSWORD: {{ $password | quote }}
  htpasswd: {{ $htpasswd | quote }}
{{- end }}
